/**
 * Asset manifest — where every external 3D asset came from and what was done to it.
 *
 * A GLB on disk carries none of this. Once a mesh has been downloaded,
 * segmented, cleaned in Blender and exported, nothing in the file says which
 * atlas release it began as, under what licence, whether a subject's imaging
 * is behind it, what units it is in, or which of its parts a scene may point at
 * by name. That information is lost at the moment of conversion unless it is
 * written down, so it is written down here, per asset, and tested.
 *
 * Two questions are deliberately kept apart:
 *
 * 1. **Is the record complete for its source type?** — `validateAssetManifest`.
 *    An imaging-derived asset must say how it was de-identified; a procedural
 *    one must say how to regenerate it; neither has to fill in the other's
 *    fields with a made-up "N/A".
 * 2. **May this asset ship to the public product?** — `assetReleaseProblems`.
 *    A licence recorded as `unknown` is a valid record of an investigation in
 *    progress. It is not a licence gate passed.
 *
 * The pipeline that produces an asset — source choice, licence and PHI review,
 * hashing, Slicer/Blender, export, validation, semantic and anatomy QA, device
 * QA, medical review, release — is `docs/asset-pipeline.md`. This file records
 * its outcome. Blender is an offline tool in that pipeline and never a runtime
 * dependency; MCP tooling is an operator's window onto it and never the record.
 *
 * Pure data and pure functions. No `three`, no DOM, no filesystem — a reader
 * for hashing is injected by whoever checks the files (`tests/asset-manifest.test.js`).
 */

export const ASSET_MANIFEST_SCHEMA_VERSION = 1;

/** Where an asset's geometry ultimately came from. Decides which conditional block is required. */
export const ASSET_SOURCE_TYPE = Object.freeze({
  /** A curated normal reference mesh or atlas release (HRA, Z-Anatomy, BodyParts3D, NIH 3D entries). */
  REFERENCE_ATLAS: 'reference-atlas',
  /** Segmented from CT/MRI or another imaging dataset. */
  IMAGING_DERIVED: 'imaging-derived',
  /** Generated by a script or generator from parameters, and reproducible from them. */
  PROCEDURAL: 'procedural',
  /** From a structural database accession (PDB and the like). */
  MOLECULAR: 'molecular',
  /** A texture, material or decoder someone else made, recorded item by item. */
  THIRD_PARTY_MATERIAL: 'third-party-material',
});

/** The three-way licence decision the strategy asks for. `unknown` is honest and is not a pass. */
export const LICENSE_DECISION = Object.freeze({
  ALLOWED: 'allowed',
  RESTRICTED: 'restricted',
  UNKNOWN: 'unknown',
});

/** A QA gate's state. `not-required` must say why in `note`. */
export const QA_STATUS = Object.freeze({
  PASSED: 'passed',
  PENDING: 'pending',
  FAILED: 'failed',
  NOT_REQUIRED: 'not-required',
});

/** Where an asset stands. Only `released` assets may be referenced by a public scene. */
export const RELEASE_STATUS = Object.freeze({
  /** Recorded, not yet through the pipeline. */
  CANDIDATE: 'candidate',
  /** Used by a Lab scene or a development harness only. */
  LAB: 'lab',
  RELEASED: 'released',
  RETIRED: 'retired',
});

const values = (enumeration) => Object.freeze(Object.values(enumeration));
export const ASSET_SOURCE_TYPE_IDS = values(ASSET_SOURCE_TYPE);
export const LICENSE_DECISION_IDS = values(LICENSE_DECISION);
export const QA_STATUS_IDS = values(QA_STATUS);
export const RELEASE_STATUS_IDS = values(RELEASE_STATUS);

/**
 * @typedef {object} AssetFile
 * @property {string} path repository-relative, or a URL for an upstream file that is not vendored
 * @property {string | null} sha256 hex. `null` only with a `note` saying why it could not be recorded
 * @property {number} [bytes]
 * @property {string} [note]
 */

/**
 * @typedef {object} AssetManifestEntry
 * @property {string} assetId stable, kebab-case; model profiles reference it
 * @property {number} schemaVersion
 * @property {string} sourceType one of ASSET_SOURCE_TYPE
 * @property {string} format e.g. `glb`
 * @property {string} organ taxonomy organ id
 * @property {string} structureScope what anatomy the asset covers, in words
 * @property {{ name: string, url: string, version: string, retrievedAt: string, note?: string }} source
 * @property {{ spdx: string, url: string, attribution: string, redistribution: string, commercialUse: string,
 *   decisionRecord: string | null, decisionNote: string }} license
 * @property {AssetFile[]} sources every upstream file, individually
 * @property {AssetFile} output the file the app loads
 * @property {{ coordinateSystem: string, units: string, extent: string, scaleNote: string }} geometry
 * @property {{ tools: string[], generator: string | null, steps: string[] }} pipeline
 * @property {{ partIdSource: string, mappingModule: string | null, partCount: number | null }} semanticParts
 * @property {string[]} acceptedSimplifications
 * @property {string[]} knownDefects
 * @property {{ triangles: number | null, materials: number | null, textures: number | null,
 *   bytes: number | null, targetDevices: string }} budget
 * @property {Record<string, { status: string, reference: string | null, note?: string }>} qa
 *   keys: `validator`, `anatomyTests`, `visualReview`, `clinicianReview`
 * @property {{ replaces: string | null, rollback: string }} replacement
 * @property {{ status: string, note: string }} release
 * @property {object} [atlas] required for reference-atlas
 * @property {object} [imaging] required for imaging-derived
 * @property {object} [procedural] required for procedural
 * @property {object} [molecular] required for molecular
 * @property {object} [material] required for third-party-material
 */

/**
 * The one external asset the product ships today, recorded from
 * `public/assets/brain/ATTRIBUTION.md`, from the file itself (hash, size,
 * mesh and triangle counts, extents read from the glTF accessors) and from
 * git history. Nothing here was taken from the upstream site: the build
 * environment did not fetch it, and the record says where that leaves the
 * source hash.
 *
 * @type {readonly AssetManifestEntry[]}
 */
export const ASSET_MANIFEST = Object.freeze([
  {
    assetId: 'brain-atlas-glb',
    schemaVersion: 1,
    sourceType: ASSET_SOURCE_TYPE.REFERENCE_ATLAS,
    format: 'glb',
    organ: 'brain',
    structureScope:
      'Gross brain anatomy: cortex, deep grey matter, diencephalon, white matter, ventricles, cerebellum, ' +
      'brainstem, plus arteries and other categories the scene does not expose.',
    source: {
      name: 'Brain Project (Itay Inbar), redistributing Z-Anatomy / BodyParts3D (DBCLS) meshes',
      url: 'https://github.com/itayinbarr/brainproject',
      version: '2929e94f521a8ddceab26bc100a98dc06b0da060',
      // The date the file entered this repository. The upstream download date
      // was not recorded at the time and is not guessed here.
      retrievedAt: '2026-09-01',
      note: 'retrievedAt is the git date the file was added (commit e344d46), not an upstream download date.',
    },
    license: {
      spdx: 'CC-BY-SA-4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
      attribution: 'Z-Anatomy contributors and BodyParts3D / DBCLS, via Brain Project by Itay Inbar',
      redistribution: LICENSE_DECISION.ALLOWED,
      commercialUse: LICENSE_DECISION.ALLOWED,
      decisionRecord: 'public/assets/brain/ATTRIBUTION.md',
      decisionNote:
        'CC BY-SA 4.0 permits redistribution and commercial use with attribution; ShareAlike binds any modified ' +
        'redistribution, and the app redistributes the GLB unchanged. Read from the licence text by the engineer ' +
        'who backfilled this record; it is not a legal review.',
    },
    sources: [
      {
        path: 'https://github.com/itayinbarr/brainproject/blob/2929e94f521a8ddceab26bc100a98dc06b0da060/',
        sha256: null,
        note:
          'ATTRIBUTION.md states the file is redistributed unchanged, so the upstream hash should equal the ' +
          'output hash, but it was not independently verified against the upstream revision.',
      },
    ],
    output: {
      path: 'public/assets/brain/brain.glb',
      sha256: '76a49ea4526a4880613aec7a02756bd7301b0b9d0680d7cae33e197b672c5453',
      bytes: 4650816,
    },
    geometry: {
      coordinateSystem: 'glTF 2.0 (right-handed, +Y up, +Z forward)',
      units: 'glTF metres as declared by the format; upstream scale not stated',
      extent: 'x 0.152, y 0.597 (1.105 to 1.702), z 0.200 across all mesh accessors',
      scaleNote:
        'The scene normalises the atlas to a target radius at load (BrainAnatomyScene), so no absolute size is claimed.',
    },
    pipeline: {
      tools: ['glTF-Transform v4.3.0 (upstream generator, per asset metadata)'],
      generator: null,
      steps: [
        'Downloaded from the upstream repository at the recorded revision.',
        'Copied into public/assets/brain/ unchanged, with the vendored Draco decoder beside it.',
      ],
    },
    semanticParts: {
      partIdSource: 'glTF node extras bx_id / bx_label / bx_side / bx_region / bx_cat / bx_source embedded upstream',
      mappingModule: 'src/data/brainAnatomy.js',
      partCount: 437,
    },
    acceptedSimplifications: [
      'Deep nuclei and white-matter structures are registered from open MNI-space atlases and are approximate.',
      'Labels are trusted from the upstream metadata; mesh boundaries are not independently validated.',
    ],
    knownDefects: [],
    budget: {
      triangles: 1383522,
      materials: 13,
      textures: 0,
      bytes: 4650816,
      targetDevices: 'Desktop and current phones; counted against the specimen-media bundle budget.',
    },
    qa: {
      validator: {
        status: QA_STATUS.NOT_REQUIRED,
        reference: null,
        note: 'Predates the pipeline. The Khronos glTF Validator has not been run on this file in this repository.',
      },
      anatomyTests: { status: QA_STATUS.PASSED, reference: 'tests/brain-anatomy.test.js' },
      visualReview: { status: QA_STATUS.PASSED, reference: 'docs/anatomy-review.md' },
      clinicianReview: { status: QA_STATUS.PENDING, reference: 'docs/clinical-reviews/registry.json' },
    },
    replacement: {
      replaces: null,
      rollback: 'git revert of the commit that changes this file; the scene loads whatever GLB is at the recorded path.',
    },
    release: {
      status: RELEASE_STATUS.RELEASED,
      note: 'Shipped with the alpha brain-anatomy scene before this manifest existed; recorded, not re-gated.',
    },
    atlas: {
      sourceObjectId: 'brainproject/brain.glb @ 2929e94f521a8ddceab26bc100a98dc06b0da060',
      derivativeTerms: 'ShareAlike: a modified redistribution must remain CC BY-SA 4.0 and keep the attribution.',
    },
  },
]);

const BY_ID = new Map(ASSET_MANIFEST.map((asset) => [asset.assetId, asset]));

/** @param {string} id */
export const assetById = (id, assets = ASSET_MANIFEST) =>
  (assets === ASSET_MANIFEST ? BY_ID.get(id) : assets.find((a) => a.assetId === id)) ?? null;

const ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const SHA256_PATTERN = /^[0-9a-f]{64}$/;
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

const nonEmpty = (value) => typeof value === 'string' && value.trim().length > 0;
const isStringList = (value) => Array.isArray(value) && value.every(nonEmpty);
const isObject = (value) => value != null && typeof value === 'object' && !Array.isArray(value);

/** The block each source type must carry, and the fields inside it that must be filled. */
export const CONDITIONAL_FIELDS = Object.freeze({
  [ASSET_SOURCE_TYPE.REFERENCE_ATLAS]: Object.freeze({ block: 'atlas', fields: ['sourceObjectId', 'derivativeTerms'] }),
  [ASSET_SOURCE_TYPE.IMAGING_DERIVED]: Object.freeze({
    block: 'imaging',
    fields: ['dataset', 'subjectProvenance', 'deidentification', 'segmentationMethod', 'registrationMethod', 'manualEdits'],
  }),
  [ASSET_SOURCE_TYPE.PROCEDURAL]: Object.freeze({
    block: 'procedural',
    fields: ['generatorVersion', 'seedOrConfig', 'inputParameters', 'regenerate'],
  }),
  [ASSET_SOURCE_TYPE.MOLECULAR]: Object.freeze({ block: 'molecular', fields: ['accession', 'assembly', 'structureVersion'] }),
  [ASSET_SOURCE_TYPE.THIRD_PARTY_MATERIAL]: Object.freeze({ block: 'material', fields: ['items'] }),
});

const QA_GATES = Object.freeze(['validator', 'anatomyTests', 'visualReview', 'clinicianReview']);

function checkFile(problems, where, name, file, { allowUrl = false } = {}) {
  if (!isObject(file)) {
    problems.push(`${where}: ${name} must be an object with path and sha256`);
    return;
  }
  if (!nonEmpty(file.path)) problems.push(`${where}: ${name}.path is missing`);
  else if (!allowUrl && /^[a-z]+:\/\//.test(file.path)) problems.push(`${where}: ${name}.path must be repository-relative, not a URL`);
  if (file.sha256 === null) {
    if (!nonEmpty(file.note)) problems.push(`${where}: ${name}.sha256 is null without a note saying why`);
  } else if (typeof file.sha256 !== 'string' || !SHA256_PATTERN.test(file.sha256)) {
    problems.push(`${where}: ${name}.sha256 must be 64 lowercase hex characters or null`);
  }
  if (file.bytes != null && !(Number.isInteger(file.bytes) && file.bytes > 0)) {
    problems.push(`${where}: ${name}.bytes must be a positive integer`);
  }
}

/**
 * Everything structurally wrong with a manifest, as readable lines.
 *
 * This is completeness for the source type, not releasability — see
 * `assetReleaseProblems` for the gate. Returned rather than thrown.
 *
 * @param {readonly AssetManifestEntry[]} assets
 * @param {{ organIds?: Set<string> }} [options]
 */
export function validateAssetManifest(assets = ASSET_MANIFEST, { organIds } = {}) {
  const problems = [];
  const seen = new Set();

  for (const asset of assets) {
    const where = `asset "${asset?.assetId ?? '(no id)'}"`;
    if (!isObject(asset)) {
      problems.push('an asset entry is not an object');
      continue;
    }
    if (!nonEmpty(asset.assetId) || !ID_PATTERN.test(asset.assetId)) problems.push(`${where}: assetId must be kebab-case`);
    else if (seen.has(asset.assetId)) problems.push(`${where}: duplicate assetId`);
    else seen.add(asset.assetId);

    if (asset.schemaVersion !== ASSET_MANIFEST_SCHEMA_VERSION) {
      problems.push(`${where}: schemaVersion must be ${ASSET_MANIFEST_SCHEMA_VERSION}`);
    }
    if (!ASSET_SOURCE_TYPE_IDS.includes(asset.sourceType)) problems.push(`${where}: unknown sourceType "${asset.sourceType}"`);
    if (!nonEmpty(asset.format)) problems.push(`${where}: format is missing`);
    if (!nonEmpty(asset.organ)) problems.push(`${where}: organ is missing`);
    else if (organIds && !organIds.has(asset.organ)) problems.push(`${where}: organ "${asset.organ}" is not in the taxonomy`);
    if (!nonEmpty(asset.structureScope)) problems.push(`${where}: structureScope is missing`);

    // Source
    if (!isObject(asset.source)) problems.push(`${where}: source is missing`);
    else {
      for (const field of ['name', 'url', 'version']) {
        if (!nonEmpty(asset.source[field])) problems.push(`${where}: source.${field} is missing`);
      }
      if (!DATE_PATTERN.test(asset.source.retrievedAt ?? '')) problems.push(`${where}: source.retrievedAt must be an ISO date`);
    }

    // Licence — the record must be complete; whether it *passes* is the gate's business.
    if (!isObject(asset.license)) problems.push(`${where}: license is missing`);
    else {
      for (const field of ['spdx', 'url', 'attribution', 'decisionNote']) {
        if (!nonEmpty(asset.license[field])) problems.push(`${where}: license.${field} is missing`);
      }
      for (const field of ['redistribution', 'commercialUse']) {
        if (!LICENSE_DECISION_IDS.includes(asset.license[field])) {
          problems.push(`${where}: license.${field} must be one of ${LICENSE_DECISION_IDS.join(' | ')}`);
        }
      }
      if (asset.license.decisionRecord !== null && !nonEmpty(asset.license.decisionRecord)) {
        problems.push(`${where}: license.decisionRecord must be a path or null`);
      }
    }

    // Files
    if (!Array.isArray(asset.sources) || asset.sources.length === 0) problems.push(`${where}: sources must list every upstream file`);
    else asset.sources.forEach((file, i) => checkFile(problems, where, `sources[${i}]`, file, { allowUrl: true }));
    checkFile(problems, where, 'output', asset.output);
    if (isObject(asset.output) && asset.output.sha256 === null) problems.push(`${where}: output.sha256 is required`);

    // Geometry, pipeline, parts
    if (!isObject(asset.geometry)) problems.push(`${where}: geometry is missing`);
    else {
      for (const field of ['coordinateSystem', 'units', 'extent', 'scaleNote']) {
        if (!nonEmpty(asset.geometry[field])) problems.push(`${where}: geometry.${field} is missing`);
      }
    }
    if (!isObject(asset.pipeline)) problems.push(`${where}: pipeline is missing`);
    else {
      if (!isStringList(asset.pipeline.tools)) problems.push(`${where}: pipeline.tools must be a list of tool versions`);
      if (asset.pipeline.generator !== null && !nonEmpty(asset.pipeline.generator)) problems.push(`${where}: pipeline.generator must be a string or null`);
      if (!isStringList(asset.pipeline.steps) || asset.pipeline.steps.length === 0) problems.push(`${where}: pipeline.steps must record the conversion`);
    }
    if (!isObject(asset.semanticParts)) problems.push(`${where}: semanticParts is missing`);
    else {
      if (!nonEmpty(asset.semanticParts.partIdSource)) problems.push(`${where}: semanticParts.partIdSource is missing`);
      if (asset.semanticParts.mappingModule !== null && !nonEmpty(asset.semanticParts.mappingModule)) {
        problems.push(`${where}: semanticParts.mappingModule must be a path or null`);
      }
      if (asset.semanticParts.partCount !== null && !(Number.isInteger(asset.semanticParts.partCount) && asset.semanticParts.partCount >= 0)) {
        problems.push(`${where}: semanticParts.partCount must be a non-negative integer or null`);
      }
    }
    if (!isStringList(asset.acceptedSimplifications)) problems.push(`${where}: acceptedSimplifications must be a list`);
    if (!isStringList(asset.knownDefects)) problems.push(`${where}: knownDefects must be a list`);

    // Budget
    if (!isObject(asset.budget)) problems.push(`${where}: budget is missing`);
    else {
      for (const field of ['triangles', 'materials', 'textures', 'bytes']) {
        const value = asset.budget[field];
        if (value !== null && !(Number.isInteger(value) && value >= 0)) problems.push(`${where}: budget.${field} must be an integer or null`);
      }
      if (!nonEmpty(asset.budget.targetDevices)) problems.push(`${where}: budget.targetDevices is missing`);
    }

    // QA
    if (!isObject(asset.qa)) problems.push(`${where}: qa is missing`);
    else {
      for (const gate of QA_GATES) {
        const entry = asset.qa[gate];
        if (!isObject(entry)) {
          problems.push(`${where}: qa.${gate} is missing`);
          continue;
        }
        if (!QA_STATUS_IDS.includes(entry.status)) problems.push(`${where}: qa.${gate}.status must be one of ${QA_STATUS_IDS.join(' | ')}`);
        if (entry.reference !== null && !nonEmpty(entry.reference)) problems.push(`${where}: qa.${gate}.reference must be a path or null`);
        if (entry.status === QA_STATUS.PASSED && entry.reference === null) problems.push(`${where}: qa.${gate} passed without a reference`);
        if (entry.status === QA_STATUS.NOT_REQUIRED && !nonEmpty(entry.note)) problems.push(`${where}: qa.${gate} is not-required without a note`);
      }
    }

    // Replacement and release
    if (!isObject(asset.replacement)) problems.push(`${where}: replacement is missing`);
    else {
      if (asset.replacement.replaces !== null && !nonEmpty(asset.replacement.replaces)) problems.push(`${where}: replacement.replaces must be an asset id or null`);
      if (!nonEmpty(asset.replacement.rollback)) problems.push(`${where}: replacement.rollback is missing`);
    }
    if (!isObject(asset.release)) problems.push(`${where}: release is missing`);
    else {
      if (!RELEASE_STATUS_IDS.includes(asset.release.status)) problems.push(`${where}: release.status must be one of ${RELEASE_STATUS_IDS.join(' | ')}`);
      if (!nonEmpty(asset.release.note)) problems.push(`${where}: release.note is missing`);
    }

    // Conditional block for the source type — and none of the others.
    const conditional = CONDITIONAL_FIELDS[asset.sourceType];
    if (conditional) {
      const block = asset[conditional.block];
      if (!isObject(block)) problems.push(`${where}: ${asset.sourceType} requires a "${conditional.block}" block`);
      else {
        for (const field of conditional.fields) {
          const value = block[field];
          const filled = Array.isArray(value) ? value.length > 0 : nonEmpty(value);
          if (!filled) problems.push(`${where}: ${conditional.block}.${field} is required for ${asset.sourceType}`);
        }
      }
      for (const [type, other] of Object.entries(CONDITIONAL_FIELDS)) {
        if (type !== asset.sourceType && asset[other.block] != null) {
          problems.push(`${where}: carries a "${other.block}" block that belongs to ${type}, not ${asset.sourceType}`);
        }
      }
    }
    if (asset.sourceType === ASSET_SOURCE_TYPE.THIRD_PARTY_MATERIAL && isObject(asset.material) && Array.isArray(asset.material.items)) {
      asset.material.items.forEach((item, i) => {
        for (const field of ['name', 'source', 'license']) {
          if (!nonEmpty(item?.[field])) problems.push(`${where}: material.items[${i}].${field} is missing`);
        }
        if (!SHA256_PATTERN.test(item?.sha256 ?? '')) problems.push(`${where}: material.items[${i}].sha256 must be 64 hex characters`);
      });
    }
  }

  // Replacement targets must exist.
  for (const asset of assets) {
    const target = asset?.replacement?.replaces;
    if (nonEmpty(target) && !assets.some((other) => other.assetId === target)) {
      problems.push(`asset "${asset.assetId}": replaces "${target}", which is not in the manifest`);
    }
  }

  return problems;
}

/**
 * Why an asset may not ship to the public product. Empty means it may.
 *
 * Separate from structural validity on purpose: a complete record of an
 * asset whose licence is still being investigated is a good record and a
 * blocked release, and a validator that reported those as one thing would
 * teach people to fill in `allowed` to make the red go away.
 *
 * Clinician review is required only when asked for: an `alpha` scene is by
 * definition awaiting review, so the caller decides from the scene's status
 * (`reviewed` / `production` require it) rather than the gate guessing.
 *
 * @param {AssetManifestEntry} asset
 * @param {{ requireClinicianReview?: boolean }} [options]
 */
export function assetReleaseProblems(asset, { requireClinicianReview = false } = {}) {
  const problems = [];
  const where = `asset "${asset?.assetId ?? '(no id)'}"`;
  const license = asset?.license ?? {};

  if (license.redistribution !== LICENSE_DECISION.ALLOWED) {
    problems.push(`${where}: redistribution is "${license.redistribution}", not allowed`);
  }
  if (license.commercialUse === LICENSE_DECISION.UNKNOWN) {
    problems.push(`${where}: commercial use has not been decided`);
  }
  if (license.decisionRecord === null) problems.push(`${where}: the licence decision has no record`);

  if (asset?.output?.sha256 == null) problems.push(`${where}: output hash is not recorded`);

  if (asset?.sourceType === ASSET_SOURCE_TYPE.IMAGING_DERIVED) {
    const confirmed = asset?.imaging?.deidentification;
    if (!nonEmpty(confirmed) || /^(no|unknown|pending)$/i.test(confirmed.trim())) {
      problems.push(`${where}: de-identification of the imaging is not confirmed`);
    }
  }

  const clinician = asset?.qa?.clinicianReview?.status;
  if (clinician === QA_STATUS.FAILED) problems.push(`${where}: clinician review failed`);
  else if (requireClinicianReview && clinician !== QA_STATUS.PASSED) {
    problems.push(`${where}: clinician review is "${clinician}", and the referencing scene claims review`);
  }
  if (asset?.qa?.anatomyTests?.status === QA_STATUS.FAILED) problems.push(`${where}: anatomy tests failed`);

  if (asset?.release?.status !== RELEASE_STATUS.RELEASED) {
    problems.push(`${where}: release status is "${asset?.release?.status}", not released`);
  }
  return problems;
}

/** @param {AssetManifestEntry} asset */
export const assetIsReleasable = (asset, options) => assetReleaseProblems(asset, options).length === 0;
