/**
 * Asset manifest — where every external 3D asset came from, what was done to
 * it, what it obliges us to, and whether it may ship.
 *
 * A GLB on disk carries none of this. Once a mesh has been downloaded,
 * segmented, cleaned in Blender and exported, nothing in the file says which
 * atlas release it began as, under what licences its parts arrived, whether a
 * subject's imaging is behind it, what units it is in, or which of its parts a
 * scene may point at by name. That information is lost at the moment of
 * conversion unless it is written down, so it is written down here, per asset,
 * and tested.
 *
 * Two questions are deliberately kept apart:
 *
 * 1. **Is the record complete and well-typed for its kind and source type?**
 *    — `validateAssetManifest`. An imaging-derived asset must say how it was
 *    de-identified; a procedural one must say how to regenerate it; a material
 *    has no geometry block to fill. Nothing is filled with a made-up "N/A".
 * 2. **May this asset ship to the public product?** — `assetReleaseProblems`.
 *    A licence decision recorded as `unknown` is a valid record of an
 *    investigation in progress. It is not a gate passed. A QA gate that has
 *    not been run is not a gate passed. A review of a *different* version of
 *    the file is not a review of this one.
 *
 * A GLB is a transport format, not a provenance. `sourceType` says where the
 * geometry came from; `format` says how it is stored; the two are independent.
 *
 * The pipeline that produces an asset is `docs/asset-pipeline.md`; this file
 * records its outcome. Blender is an offline tool in that pipeline and never a
 * runtime dependency; MCP tooling is an operator's window onto it and never
 * the record.
 *
 * Pure data and pure functions. No `three`, no DOM, no filesystem — anything
 * that has to look at a file (hashes, whether a referenced path exists) is
 * injected by the caller, which for this repository is `tests/asset-manifest.test.js`.
 */

export const ASSET_MANIFEST_SCHEMA_VERSION = 1;

/** What the file is. Decides which structural blocks the record must carry. */
export const ASSET_KIND = Object.freeze({
  /** Geometry a scene draws. Has coordinates, units, semantic parts and a triangle budget. */
  MESH: 'mesh',
  /** A texture, material definition or similar that a mesh consumes. Has no geometry of its own. */
  MATERIAL: 'material',
});

/** Where an asset's content ultimately came from. Decides which conditional block is required. */
export const ASSET_SOURCE_TYPE = Object.freeze({
  /** A curated normal reference mesh or atlas release (HRA, Z-Anatomy, BodyParts3D, NIH 3D entries). */
  REFERENCE_ATLAS: 'reference-atlas',
  /** Segmented from CT/MRI or another imaging dataset. */
  IMAGING_DERIVED: 'imaging-derived',
  /** Generated by a script or generator from parameters, and reproducible from them. Still procedural when stored as a GLB. */
  PROCEDURAL: 'procedural',
  /** From a structural database accession (PDB and the like). */
  MOLECULAR: 'molecular',
  /** Someone else's texture or material, recorded on its own terms. Materials only. */
  THIRD_PARTY: 'third-party',
});

/** The three-way licence decision. `unknown` is honest and is not a pass. */
export const LICENSE_DECISION = Object.freeze({
  ALLOWED: 'allowed',
  RESTRICTED: 'restricted',
  UNKNOWN: 'unknown',
});

/** Who made the licence assessment. An engineering reading is not legal advice and says so. */
export const ASSESSMENT_BASIS = Object.freeze({
  ENGINEERING: 'engineering',
  LEGAL: 'legal',
});

/** What a licence or data-use term requires of us. Each obligation is checked at release. */
export const OBLIGATION_KIND = Object.freeze({
  /** Credit the named authors and sources. */
  ATTRIBUTION: 'attribution',
  /** A modified redistribution must carry the same licence. */
  SHARE_ALIKE: 'share-alike',
  /** A specific acknowledgment text a data provider requires. */
  ACKNOWLEDGMENT: 'acknowledgment',
  /** Keep the upstream licence notice with the file. */
  NOTICE_RETENTION: 'notice-retention',
});

export const OBLIGATION_STATUS = Object.freeze({
  SATISFIED: 'satisfied',
  PENDING: 'pending',
});

/**
 * A QA gate's state. There is no free-text waiver: `not-applicable` is
 * accepted only where `QA_APPLIES` says the gate does not apply to this kind
 * of asset, and is a problem everywhere else.
 */
export const QA_STATUS = Object.freeze({
  PASSED: 'passed',
  PENDING: 'pending',
  FAILED: 'failed',
  NOT_APPLICABLE: 'not-applicable',
});

/**
 * The five gates, and what each one actually establishes. They are separate
 * because a hash test, a browser render and a clinician's reading of the
 * anatomy are three different facts, and one word for all three would let the
 * cheapest of them stand in for the others.
 */
export const QA_GATE = Object.freeze({
  /** The file is well-formed: the Khronos glTF Validator at a pinned version, errors and warnings counted. */
  FORMAT_VALIDATION: 'formatValidation',
  /** The parts a scene points at are present and named as the metadata adapter expects (a test). Not anatomy. */
  SEMANTIC_INTEGRITY: 'semanticIntegrity',
  /** An anatomist or clinician judged the geometry and labels. A test cannot do this. */
  ANATOMY_EXPERT_REVIEW: 'anatomyExpertReview',
  /** A real browser rendered the scene with this exact file: browser, viewport, scene, date, commit recorded. */
  VISUAL_REVIEW: 'visualReview',
  /** Clinical review of the scene that uses the asset, through the clinical-review registry. */
  CLINICIAN_REVIEW: 'clinicianReview',
});

export const QA_GATE_IDS = Object.freeze(Object.values(QA_GATE));

/**
 * Which gates apply to which kind of asset. This is the only route to
 * `not-applicable`, and it is data rather than a note so that a reviewer can
 * see the whole rule in one place.
 */
export const QA_APPLIES = Object.freeze({
  [ASSET_KIND.MESH]: Object.freeze(QA_GATE_IDS),
  [ASSET_KIND.MATERIAL]: Object.freeze([QA_GATE.FORMAT_VALIDATION, QA_GATE.VISUAL_REVIEW]),
});

/**
 * Gates whose passing state is tied to one exact file: they must name the hash
 * they were run against, and the gate refuses them when the output has moved
 * since.
 *
 * `anatomyExpertReview` belongs here for the reason the others do, and more
 * so: it is the only gate that can establish anatomical correctness, and no
 * other gate can stand in for it. A replaced mesh updates the format, semantic
 * and visual records, and an expert sign-off left unbound would silently carry
 * over to geometry the expert never saw.
 *
 * `clinicianReview` is deliberately not here. It is a judgement about the
 * *scene*, and its staleness is already owned by the review registry's
 * `stalePaths` against a reviewed commit
 * (`docs/clinical-reviews/registry.json`, `src/catalog/clinicalReview.js`).
 * Binding it to a file hash as well would put one obligation in two places.
 */
export const HASH_BOUND_GATES = Object.freeze([
  QA_GATE.FORMAT_VALIDATION,
  QA_GATE.SEMANTIC_INTEGRITY,
  QA_GATE.ANATOMY_EXPERT_REVIEW,
  QA_GATE.VISUAL_REVIEW,
]);

/**
 * Gates that a scene at `alpha` may ship with still `pending`, because alpha
 * *means* "awaiting review". `failed` blocks at every status. Everything not
 * listed here must be `passed` for any public scene.
 */
export const REVIEW_GATES_DEFERRABLE_AT_ALPHA = Object.freeze([
  QA_GATE.ANATOMY_EXPERT_REVIEW,
  QA_GATE.CLINICIAN_REVIEW,
]);

/** Structured rather than a sentence, so the gate never has to parse prose. */
export const DEIDENTIFICATION_STATUS = Object.freeze({
  CONFIRMED: 'confirmed',
  PENDING: 'pending',
  NOT_CONFIRMED: 'not-confirmed',
});

/** Where an asset stands. Only `released` assets may be referenced by a public scene. */
export const RELEASE_STATUS = Object.freeze({
  /** Recorded, not yet through the pipeline. */
  CANDIDATE: 'candidate',
  /** Used by a Lab scene or a development harness only. */
  LAB: 'lab',
  RELEASED: 'released',
  RETIRED: 'retired',
});

/** Scene statuses at which the deferrable review gates may still be pending. */
const STATUSES_AWAITING_REVIEW = new Set(['alpha']);

const values = (enumeration) => Object.freeze(Object.values(enumeration));
export const ASSET_KIND_IDS = values(ASSET_KIND);
export const ASSET_SOURCE_TYPE_IDS = values(ASSET_SOURCE_TYPE);
export const LICENSE_DECISION_IDS = values(LICENSE_DECISION);
export const ASSESSMENT_BASIS_IDS = values(ASSESSMENT_BASIS);
export const OBLIGATION_KIND_IDS = values(OBLIGATION_KIND);
export const OBLIGATION_STATUS_IDS = values(OBLIGATION_STATUS);
export const QA_STATUS_IDS = values(QA_STATUS);
export const DEIDENTIFICATION_STATUS_IDS = values(DEIDENTIFICATION_STATUS);
export const RELEASE_STATUS_IDS = values(RELEASE_STATUS);

/**
 * @typedef {object} AssetFile
 * @property {string} path repository-relative, or a URL for an upstream file that is not vendored
 * @property {string | null} sha256 hex. `null` only with a `note` saying why it could not be recorded;
 *   a released asset must have every hash
 * @property {string} [gitBlobSha] the upstream git blob id, when the source is a git repository
 * @property {number} [bytes]
 * @property {string} [verifiedAt] ISO timestamp of the download that produced the hash
 * @property {string} [note]
 */

/**
 * @typedef {object} LicenseObligation
 * @property {string} id
 * @property {string} kind one of OBLIGATION_KIND
 * @property {string[]} components component ids the obligation comes from
 * @property {string} requirement what must be done, in words
 * @property {string} status one of OBLIGATION_STATUS
 * @property {string | null} satisfiedBy repository-relative path of the notice or record that discharges it
 * @property {string} displayedVia how a reader of the product reaches that notice
 */

/**
 * @typedef {object} AssetManifestEntry
 * @property {string} assetId stable, kebab-case; model profiles reference it
 * @property {number} schemaVersion
 * @property {string} kind one of ASSET_KIND
 * @property {string} sourceType one of ASSET_SOURCE_TYPE
 * @property {string} format storage format, e.g. `glb`; says nothing about provenance
 * @property {string[]} organs taxonomy organ ids the asset covers. `whole-body` marks a systemic context asset
 * @property {string} structureScope what anatomy the asset covers, in words
 * @property {{ name: string, url: string, fileUrl: string | null, revision: string, retrievedAt: string | null,
 *   retrievedAtNote?: string, introducedAt: string, introducedIn: string }} source
 * @property {{ spdx: string, url: string, attribution: string, redistribution: string, commercialUse: string,
 *   assessment: string, assessedAt: string, decisionRecord: string | null, decisionNote: string,
 *   obligations: LicenseObligation[] }} license
 * @property {{ id: string, name: string, url: string, license: string, role: string,
 *   additionalTerms: string | null }[]} components every distinct source the asset is composed of
 * @property {AssetFile[]} sources every upstream file, individually
 * @property {AssetFile} output the file the app loads
 * @property {{ coordinateSystem: string, units: string, extent: string, scaleNote: string }} [geometry] mesh only
 * @property {{ tools: string[], generator: string | null, steps: string[] }} pipeline
 * @property {{ partIdSource: string, mappingModule: string | null, partCount: number | null }} [semanticParts] mesh only
 * @property {string[]} acceptedSimplifications
 * @property {string[]} knownDefects
 * @property {{ triangles: number | null, materials: number | null, textures: number | null,
 *   bytes: number | null, targetDevices: string }} budget
 * @property {Record<string, object>} qa one entry per QA_GATE (see the brain record for the shape of each)
 * @property {{ replaces: string | null, rollback: string }} replacement
 * @property {{ status: string, note: string }} release
 * @property {object} [atlas] required for reference-atlas
 * @property {object} [imaging] required for imaging-derived
 * @property {object} [procedural] required for procedural
 * @property {object} [molecular] required for molecular
 * @property {object} [thirdParty] required for third-party
 */

/**
 * The one external asset the product ships today.
 *
 * Every value below was measured in this repository or read from the upstream
 * repository at the recorded revision on 2026-09-06: the upstream file was
 * downloaded and hashed (identical to the vendored copy), the Khronos glTF
 * Validator was run at a pinned version on both the file and a Draco-decoded
 * derivative, the components and their licences were read from the upstream
 * `LICENSE`, `README.md` and `docs/registration.md`, and the brain scene was
 * rendered in a real browser. The procedure and raw numbers are in
 * `docs/asset-qa/brain-atlas-glb.md`. What was *not* done — an anatomist's
 * review, a clinician's sign-off, a legal reading of the licences — is
 * recorded as not done.
 *
 * @type {readonly AssetManifestEntry[]}
 */
export const ASSET_MANIFEST = Object.freeze([
  {
    assetId: 'brain-atlas-glb',
    schemaVersion: 1,
    kind: ASSET_KIND.MESH,
    sourceType: ASSET_SOURCE_TYPE.REFERENCE_ATLAS,
    format: 'glb',
    organs: ['brain'],
    structureScope:
      'Gross brain anatomy: cortex, deep grey matter, diencephalon, white matter, ventricles, cerebellum, ' +
      'brainstem, plus arteries, venous sinuses, meninges and cranial nerves the scene does not expose.',
    source: {
      name: 'Brain Project (Itay Inbar), brain-atlas/models/brain.glb',
      url: 'https://github.com/itayinbarr/brainproject',
      fileUrl:
        'https://raw.githubusercontent.com/itayinbarr/brainproject/2929e94f521a8ddceab26bc100a98dc06b0da060/brain-atlas/models/brain.glb',
      revision: '2929e94f521a8ddceab26bc100a98dc06b0da060',
      // The original download date was not recorded when the file was added,
      // and is not invented. `introducedAt` is the git date the file entered
      // this repository; `sources[0].verifiedAt` is the re-download that
      // confirmed the hash.
      retrievedAt: null,
      retrievedAtNote: 'Original download date not recorded; the hash was re-verified against upstream on 2026-09-06.',
      introducedAt: '2026-09-01',
      introducedIn: 'e344d465de416d5a40a0cbb8b9d6b8d0c2850185',
    },
    license: {
      spdx: 'CC-BY-SA-4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
      attribution:
        'Brain Project by Itay Inbar; Z-Anatomy contributors and BodyParts3D © The Database Center for Life Science (DBCLS); ' +
        'CIT168 subcortical and amygdala atlases (Pauli, Nili & Tyszka 2018; Tyszka & Pauli 2016); Najdenovska et al. 2018; ' +
        'Neudorfer et al. 2020; HCP1065 tract templates (Yeh 2022) built on Human Connectome Project WU-Minn data.',
      redistribution: LICENSE_DECISION.ALLOWED,
      commercialUse: LICENSE_DECISION.ALLOWED,
      assessment: ASSESSMENT_BASIS.ENGINEERING,
      assessedAt: '2026-09-06',
      decisionRecord: 'public/assets/brain/ATTRIBUTION.md',
      decisionNote:
        'The upstream project licenses the combined model CC BY-SA 4.0 and states its components are CC BY 4.0 or ' +
        'CC BY-SA 4.0, which permit redistribution and commercial use. "allowed" here is conditional on the obligations ' +
        'below being discharged: attribution to every component, ShareAlike on any modified redistribution, and the ' +
        'WU-Minn HCP acknowledgment for the HCP1065-derived tracts. This is an engineering assessment from the licence ' +
        'texts as published upstream, not a legal review, and the upstream statements were not verified against each ' +
        'component\'s own publisher.',
      obligations: [
        {
          id: 'attribution',
          kind: OBLIGATION_KIND.ATTRIBUTION,
          components: [
            'brainproject',
            'z-anatomy-bodyparts3d',
            'cit168-subcortical',
            'cit168-amygdala',
            'najdenovska-2018',
            'neudorfer-2020',
            'hcp1065-tracts',
          ],
          requirement: 'Credit each component and its authors wherever the model is redistributed.',
          status: OBLIGATION_STATUS.SATISFIED,
          satisfiedBy: 'public/assets/brain/ATTRIBUTION.md',
          displayedVia:
            'Served beside the asset; linked from the Trust page as a source of the brain-anatomy review record; ' +
            'linked from docs/model-cards/brain-anatomy.md.',
        },
        {
          id: 'share-alike',
          kind: OBLIGATION_KIND.SHARE_ALIKE,
          components: ['z-anatomy-bodyparts3d', 'cit168-amygdala', 'najdenovska-2018', 'hcp1065-tracts'],
          requirement:
            'Any modified redistribution of the model must remain under CC BY-SA 4.0 and keep the attribution. ' +
            'The app redistributes the file unchanged; the notice states the condition for anyone who modifies it.',
          status: OBLIGATION_STATUS.SATISFIED,
          satisfiedBy: 'public/assets/brain/ATTRIBUTION.md',
          displayedVia: 'Same notice as the attribution.',
        },
        {
          id: 'hcp-acknowledgment',
          kind: OBLIGATION_KIND.ACKNOWLEDGMENT,
          components: ['hcp1065-tracts'],
          requirement:
            'Include the WU-Minn Human Connectome Project acknowledgment wherever HCP-derived data are redistributed, ' +
            'and redistribute it under the same terms.',
          status: OBLIGATION_STATUS.SATISFIED,
          satisfiedBy: 'public/assets/brain/ATTRIBUTION.md',
          displayedVia: 'Same notice as the attribution.',
        },
        {
          id: 'notice-retention',
          kind: OBLIGATION_KIND.NOTICE_RETENTION,
          components: ['brainproject'],
          requirement: 'Keep the upstream licence notice with the .glb (upstream LICENSE: "keep this notice with the .glb").',
          status: OBLIGATION_STATUS.SATISFIED,
          satisfiedBy: 'public/assets/brain/ATTRIBUTION.md',
          displayedVia: 'The notice lives in the same directory as the file.',
        },
      ],
    },
    components: [
      {
        id: 'brainproject',
        name: 'Brain Project (viewer, export scripts, composed model)',
        url: 'https://github.com/itayinbarr/brainproject',
        license: 'CC-BY-SA-4.0',
        role: 'Composition, Blender export, Draco compression; the viewer code is Apache-2.0 and is not used here.',
        additionalTerms: null,
      },
      {
        id: 'z-anatomy-bodyparts3d',
        name: 'Z-Anatomy, built on BodyParts3D (DBCLS)',
        url: 'https://github.com/Z-Anatomy',
        license: 'CC-BY-SA-4.0',
        role: 'Surface meshes: cortex, ventricles, brainstem, cerebellum, vessels, nerves.',
        additionalTerms:
          'Upstream states CC BY-SA 4.0 for the combined work; BodyParts3D itself is published by DBCLS under CC BY-SA 2.1 Japan, ' +
          'which was not separately assessed here.',
      },
      {
        id: 'cit168-subcortical',
        name: 'CIT168 subcortical atlas (Pauli, Nili & Tyszka 2018, Scientific Data)',
        url: 'https://osf.io/jkzwp/',
        license: 'CC-BY-4.0',
        role: 'Registered deep nuclei: globus pallidus split, subthalamic nucleus, substantia nigra, nucleus accumbens.',
        additionalTerms: null,
      },
      {
        id: 'cit168-amygdala',
        name: 'CIT168 amygdala atlas (Tyszka & Pauli 2016)',
        url: 'https://osf.io/hksa6/',
        license: 'CC-BY-SA-4.0',
        role: 'Registered amygdala functional groups.',
        additionalTerms: null,
      },
      {
        id: 'najdenovska-2018',
        name: 'Najdenovska et al. 2018, in-vivo probabilistic thalamic atlas (Scientific Data)',
        url: 'https://doi.org/10.5281/zenodo.1405484',
        license: 'CC-BY-SA-4.0',
        role: 'Registered thalamic nuclei groups.',
        additionalTerms: null,
      },
      {
        id: 'neudorfer-2020',
        name: 'Neudorfer et al. 2020, hypothalamic region atlas (Scientific Data)',
        url: 'https://doi.org/10.5281/zenodo.3942115',
        license: 'CC-BY-4.0',
        role: 'Registered hypothalamic zones.',
        additionalTerms: null,
      },
      {
        id: 'hcp1065-tracts',
        name: 'HCP1065 population-averaged tractography atlas (Yeh 2022), built on WU-Minn Human Connectome Project data',
        url: 'https://brain.labsolver.org/hcp_trk_atlas.html',
        license: 'CC-BY-SA-4.0',
        role: 'Centerlines for the white-matter tract tubes.',
        additionalTerms:
          'WU-Minn HCP open-access data use terms: the HCP acknowledgment must accompany redistribution of derived data, ' +
          'and redistribution is under the same terms. Licence as stated in upstream docs/registration.md.',
      },
    ],
    sources: [
      {
        path: 'https://raw.githubusercontent.com/itayinbarr/brainproject/2929e94f521a8ddceab26bc100a98dc06b0da060/brain-atlas/models/brain.glb',
        sha256: '76a49ea4526a4880613aec7a02756bd7301b0b9d0680d7cae33e197b672c5453',
        gitBlobSha: 'c80dd62202b5cf8a2a43c7a019311781bd95457c',
        bytes: 4650816,
        verifiedAt: '2026-09-06T04:03:21Z',
        note: 'Downloaded from the raw URL at the pinned revision and compared byte-for-byte with the vendored file: identical.',
      },
    ],
    output: {
      path: 'public/assets/brain/brain.glb',
      sha256: '76a49ea4526a4880613aec7a02756bd7301b0b9d0680d7cae33e197b672c5453',
      bytes: 4650816,
    },
    geometry: {
      coordinateSystem: 'glTF 2.0 (right-handed, +Y up, +Z forward)',
      units: 'glTF metres as declared by the format; upstream scale not stated',
      extent: 'x 0.152, y 0.597 (1.105 to 1.702), z 0.200 across all mesh accessors',
      scaleNote:
        'The scene normalises the atlas to a target radius at load (BrainAnatomyScene), so no absolute size is claimed.',
    },
    pipeline: {
      tools: ['Blender (upstream export_brain.py)', 'glTF-Transform v4.3.0 (upstream: dedup, weld, draco)'],
      generator: null,
      steps: [
        'Upstream: exported from the Z-Anatomy .blend, merged with atlas-registered nuclei and HCP1065 tract tubes, then dedup → weld → Draco.',
        'Here: downloaded from the upstream repository at the recorded revision and copied into public/assets/brain/ unchanged, with the vendored Draco decoder beside it.',
      ],
    },
    semanticParts: {
      partIdSource: 'glTF node extras bx_id / bx_label / bx_side / bx_region / bx_cat / bx_source embedded upstream',
      mappingModule: 'src/data/brainAnatomy.js',
      partCount: 437,
    },
    acceptedSimplifications: [
      'Deep nuclei, hypothalamic zones and tracts are a registration approximation across several MNI-space population atlases. The upstream ~7.2 mm figure often cited for this is the red nucleus\'s position difference in a check that excluded it from registration; it is not a boundary or maximum error for every registered structure, and this repository has not independently verified it against the shipped asset.',
      'Labels are trusted from the upstream metadata; mesh boundaries are not independently validated.',
    ],
    knownDefects: [],
    budget: {
      triangles: 1383522,
      materials: 13,
      textures: 0,
      bytes: 4650816,
      targetDevices: 'Desktop and current phones; counted against the specimen-media bundle budget.',
    },
    qa: {
      formatValidation: {
        status: QA_STATUS.PASSED,
        tool: 'Khronos glTF Validator (npm gltf-validator)',
        toolVersion: '2.0.0-dev.3.10',
        assetSha256: '76a49ea4526a4880613aec7a02756bd7301b0b9d0680d7cae33e197b672c5453',
        checkedAt: '2026-09-06T04:03:52Z',
        errors: 0,
        warnings: 0,
        infos: 744,
        scope:
          'The validator does not inspect KHR_draco_mesh_compression payloads (1 UNSUPPORTED_EXTENSION info; 743 UNUSED_OBJECT infos ' +
          'for 563 bufferViews and 180 meshes). A Draco-decoded derivative made with glTF-Transform 4.5.0 was validated separately: ' +
          '0 errors, 0 warnings, 180 infos, same triangle and vertex counts.',
        reference: 'docs/asset-qa/brain-atlas-glb.md',
      },
      semanticIntegrity: {
        status: QA_STATUS.PASSED,
        assetSha256: '76a49ea4526a4880613aec7a02756bd7301b0b9d0680d7cae33e197b672c5453',
        reference: 'tests/brain-anatomy.test.js',
        scope:
          'Hash, node count (437), selectable count (271), required labels present, metadata fields the adapter reads, ' +
          'and the licence notice. This is a test of the file and the adapter, not of the anatomy.',
      },
      anatomyExpertReview: {
        status: QA_STATUS.PENDING,
        reference: 'docs/clinical-reviews/registry.json',
        scope:
          'No anatomist or clinician has reviewed the geometry or the label set in this repository. The engineering ' +
          'render in docs/anatomy-review.md §3 checked gross orientation and relationships, not the atlas itself.',
      },
      visualReview: {
        status: QA_STATUS.PASSED,
        assetSha256: '76a49ea4526a4880613aec7a02756bd7301b0b9d0680d7cae33e197b672c5453',
        reference: 'docs/asset-qa/brain-atlas-glb.md',
        browser: 'Chromium 141.0.7390.37 (Playwright chromium-1194 build, headless, SwiftShader WebGL2)',
        viewport: '1440x900',
        scene: 'brain-anatomy',
        commit: 'c170e30a2086c837e5af55b20b295bbd9ab9b196',
        reviewedAt: '2026-09-06',
        scope:
          'Engineering render verification at 1440x900: the scene loads this file, the loading veil clears, 397 structures ' +
          'are reported, the atlas is drawn and both default annotations anchor to structures; the only console error is the ' +
          'offline-blocked Google Fonts request. Not an anatomical judgement.',
      },
      clinicianReview: {
        status: QA_STATUS.PENDING,
        reference: 'docs/clinical-reviews/registry.json',
        scope: 'The brain-anatomy review record is `pending`; this gate follows it.',
      },
    },
    replacement: {
      replaces: null,
      rollback: 'git revert of the commit that changes this file; the scene loads whatever GLB is at the recorded path.',
    },
    release: {
      status: RELEASE_STATUS.RELEASED,
      note:
        'Shipped with the alpha brain-anatomy scene since 2026-09-01 and re-judged against this gate on 2026-09-06: ' +
        'releasable for an alpha scene only, because the expert and clinician reviews are pending.',
    },
    atlas: {
      sourceObjectId: 'itayinbarr/brainproject: brain-atlas/models/brain.glb @ 2929e94f521a8ddceab26bc100a98dc06b0da060',
      derivativeTerms: 'ShareAlike: a modified redistribution must remain CC BY-SA 4.0 and keep the attribution.',
    },
  },
]);

const BY_ID = new Map(ASSET_MANIFEST.map((asset) => [asset.assetId, asset]));

/** @param {string} id */
export const assetById = (id, assets = ASSET_MANIFEST) =>
  (assets === ASSET_MANIFEST ? BY_ID.get(id) : assets.find((a) => a?.assetId === id)) ?? null;

/** Kind and source type are independent; this is the one combination that is not allowed. */
export const sourceTypeAllowedForKind = (kind, sourceType) =>
  kind === ASSET_KIND.MATERIAL ? true : sourceType !== ASSET_SOURCE_TYPE.THIRD_PARTY;

const ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const SHA256_PATTERN = /^[0-9a-f]{64}$/;
const GIT_SHA_PATTERN = /^[0-9a-f]{40}$/;
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
const TIMESTAMP_PATTERN = /^\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z)?$/;
const URL_PATTERN = /^[a-z]+:\/\//;

const nonEmpty = (value) => typeof value === 'string' && value.trim().length > 0;
const isStringList = (value) => Array.isArray(value) && value.every(nonEmpty);
const isObject = (value) => value != null && typeof value === 'object' && !Array.isArray(value);
const isCount = (value) => Number.isInteger(value) && value >= 0;

/** A repository-relative path: no URL scheme, no leading slash, no parent traversal. */
export const isRepositoryPath = (value) =>
  nonEmpty(value) &&
  !URL_PATTERN.test(value) &&
  !value.startsWith('/') &&
  !value.split('/').some((segment) => segment === '..' || segment === '');

/** The block each source type must carry, and the fields inside it that must be filled. */
export const CONDITIONAL_FIELDS = Object.freeze({
  [ASSET_SOURCE_TYPE.REFERENCE_ATLAS]: Object.freeze({ block: 'atlas', fields: ['sourceObjectId', 'derivativeTerms'] }),
  [ASSET_SOURCE_TYPE.IMAGING_DERIVED]: Object.freeze({
    block: 'imaging',
    fields: ['dataset', 'subjectProvenance', 'deidentification', 'segmentationMethod', 'registrationMethod', 'manualEdits'],
  }),
  [ASSET_SOURCE_TYPE.PROCEDURAL]: Object.freeze({
    block: 'procedural',
    fields: ['generatorVersion', 'seedOrConfig', 'inputParameters', 'regenerate'],
  }),
  [ASSET_SOURCE_TYPE.MOLECULAR]: Object.freeze({ block: 'molecular', fields: ['accession', 'assembly', 'structureVersion'] }),
  [ASSET_SOURCE_TYPE.THIRD_PARTY]: Object.freeze({ block: 'thirdParty', fields: ['upstreamItem', 'termsUrl'] }),
});

function checkFile(problems, where, name, file, { allowUrl = false } = {}) {
  if (!isObject(file)) {
    problems.push(`${where}: ${name} must be an object with path and sha256`);
    return;
  }
  if (!nonEmpty(file.path)) problems.push(`${where}: ${name}.path is missing`);
  else if (!allowUrl && !isRepositoryPath(file.path)) problems.push(`${where}: ${name}.path must be repository-relative, not a URL`);
  if (file.sha256 === null) {
    if (!nonEmpty(file.note)) problems.push(`${where}: ${name}.sha256 is null without a note saying why`);
  } else if (typeof file.sha256 !== 'string' || !SHA256_PATTERN.test(file.sha256)) {
    problems.push(`${where}: ${name}.sha256 must be 64 lowercase hex characters or null`);
  }
  if (file.gitBlobSha != null && !GIT_SHA_PATTERN.test(file.gitBlobSha)) problems.push(`${where}: ${name}.gitBlobSha must be 40 hex characters`);
  if (file.bytes != null && !(Number.isInteger(file.bytes) && file.bytes > 0)) problems.push(`${where}: ${name}.bytes must be a positive integer`);
  if (file.verifiedAt != null && !TIMESTAMP_PATTERN.test(file.verifiedAt)) problems.push(`${where}: ${name}.verifiedAt must be an ISO date or timestamp`);
}

function checkQaGate(problems, where, asset, gate) {
  const entry = asset.qa?.[gate];
  const applies = (QA_APPLIES[asset.kind] ?? []).includes(gate);
  if (!isObject(entry)) {
    problems.push(`${where}: qa.${gate} is missing`);
    return;
  }
  if (!QA_STATUS_IDS.includes(entry.status)) {
    problems.push(`${where}: qa.${gate}.status must be one of ${QA_STATUS_IDS.join(' | ')}`);
    return;
  }
  if (entry.status === QA_STATUS.NOT_APPLICABLE && applies) {
    problems.push(`${where}: qa.${gate} applies to a ${asset.kind} asset and cannot be not-applicable`);
  }
  if (entry.status !== QA_STATUS.NOT_APPLICABLE && !applies) {
    problems.push(`${where}: qa.${gate} does not apply to a ${asset.kind} asset and must be not-applicable`);
  }
  if (entry.reference != null && !isRepositoryPath(entry.reference)) {
    problems.push(`${where}: qa.${gate}.reference must be a repository path or null`);
  }
  if (entry.status === QA_STATUS.PASSED || entry.status === QA_STATUS.FAILED) {
    if (entry.reference == null) problems.push(`${where}: qa.${gate} ${entry.status} without a reference`);
  }
  if (entry.status === QA_STATUS.PASSED) {
    if (HASH_BOUND_GATES.includes(gate) && !SHA256_PATTERN.test(entry.assetSha256 ?? '')) {
      problems.push(`${where}: qa.${gate} passed without naming the asset hash it was run against`);
    }
    if (gate === QA_GATE.FORMAT_VALIDATION) {
      for (const field of ['tool', 'toolVersion', 'scope']) {
        if (!nonEmpty(entry[field])) problems.push(`${where}: qa.formatValidation.${field} is missing`);
      }
      for (const field of ['errors', 'warnings']) {
        if (!isCount(entry[field])) problems.push(`${where}: qa.formatValidation.${field} must be a count`);
      }
      if (!TIMESTAMP_PATTERN.test(entry.checkedAt ?? '')) problems.push(`${where}: qa.formatValidation.checkedAt must be an ISO timestamp`);
    }
    if (gate === QA_GATE.VISUAL_REVIEW) {
      for (const field of ['browser', 'viewport', 'scene', 'scope']) {
        if (!nonEmpty(entry[field])) problems.push(`${where}: qa.visualReview.${field} is missing`);
      }
      if (!GIT_SHA_PATTERN.test(entry.commit ?? '')) problems.push(`${where}: qa.visualReview.commit must be a 40-character commit`);
      if (!DATE_PATTERN.test(entry.reviewedAt ?? '')) problems.push(`${where}: qa.visualReview.reviewedAt must be an ISO date`);
    }
  }
}

/**
 * Everything structurally wrong with a manifest, as readable lines.
 *
 * This is completeness and well-typedness for the asset's kind and source
 * type, not releasability — see `assetReleaseProblems` for the gate. Returned
 * rather than thrown, and it must never throw on malformed input: a record
 * that is wrong in three ways gets three lines.
 *
 * @param {readonly AssetManifestEntry[]} assets
 * @param {{ organIds?: Set<string> }} [options]
 */
export function validateAssetManifest(assets = ASSET_MANIFEST, { organIds } = {}) {
  const problems = [];
  const seen = new Set();
  if (!Array.isArray(assets)) return ['the asset manifest is not an array'];

  for (const asset of assets) {
    const where = `asset "${isObject(asset) && nonEmpty(asset.assetId) ? asset.assetId : '(no id)'}"`;
    if (!isObject(asset)) {
      problems.push('an asset entry is not an object');
      continue;
    }
    if (!nonEmpty(asset.assetId) || !ID_PATTERN.test(asset.assetId)) problems.push(`${where}: assetId must be kebab-case`);
    else if (seen.has(asset.assetId)) problems.push(`${where}: duplicate assetId`);
    else seen.add(asset.assetId);

    if (asset.schemaVersion !== ASSET_MANIFEST_SCHEMA_VERSION) {
      problems.push(`${where}: schemaVersion must be ${ASSET_MANIFEST_SCHEMA_VERSION}`);
    }
    const kindKnown = ASSET_KIND_IDS.includes(asset.kind);
    if (!kindKnown) problems.push(`${where}: unknown kind "${asset.kind}"`);
    if (!ASSET_SOURCE_TYPE_IDS.includes(asset.sourceType)) problems.push(`${where}: unknown sourceType "${asset.sourceType}"`);
    else if (kindKnown && !sourceTypeAllowedForKind(asset.kind, asset.sourceType)) {
      problems.push(`${where}: a ${asset.kind} asset cannot have sourceType "${asset.sourceType}"`);
    }
    if (!nonEmpty(asset.format)) problems.push(`${where}: format is missing`);
    if (!isStringList(asset.organs) || asset.organs.length === 0) problems.push(`${where}: organs must be a non-empty list of organ ids`);
    else {
      if (new Set(asset.organs).size !== asset.organs.length) problems.push(`${where}: organs has duplicates`);
      if (organIds) {
        for (const organ of asset.organs) {
          if (!organIds.has(organ)) problems.push(`${where}: organ "${organ}" is not in the taxonomy`);
        }
      }
    }
    if (!nonEmpty(asset.structureScope)) problems.push(`${where}: structureScope is missing`);

    // Source
    if (!isObject(asset.source)) problems.push(`${where}: source is missing`);
    else {
      for (const field of ['name', 'url', 'revision']) {
        if (!nonEmpty(asset.source[field])) problems.push(`${where}: source.${field} is missing`);
      }
      if (asset.source.fileUrl !== null && !nonEmpty(asset.source.fileUrl)) problems.push(`${where}: source.fileUrl must be a URL or null`);
      if (asset.source.retrievedAt === null) {
        if (!nonEmpty(asset.source.retrievedAtNote)) problems.push(`${where}: source.retrievedAt is null without a retrievedAtNote`);
      } else if (!DATE_PATTERN.test(asset.source.retrievedAt ?? '')) {
        problems.push(`${where}: source.retrievedAt must be an ISO date or null`);
      }
      if (!DATE_PATTERN.test(asset.source.introducedAt ?? '')) problems.push(`${where}: source.introducedAt must be an ISO date`);
      if (!GIT_SHA_PATTERN.test(asset.source.introducedIn ?? '')) problems.push(`${where}: source.introducedIn must be a 40-character commit`);
    }

    // Components
    const componentIds = new Set();
    if (!Array.isArray(asset.components)) problems.push(`${where}: components must be a list`);
    else {
      asset.components.forEach((component, i) => {
        const at = `components[${i}]`;
        if (!isObject(component)) {
          problems.push(`${where}: ${at} is not an object`);
          return;
        }
        for (const field of ['id', 'name', 'url', 'license', 'role']) {
          if (!nonEmpty(component[field])) problems.push(`${where}: ${at}.${field} is missing`);
        }
        if (component.additionalTerms !== null && !nonEmpty(component.additionalTerms)) {
          problems.push(`${where}: ${at}.additionalTerms must be a string or null`);
        }
        if (nonEmpty(component.id)) {
          if (componentIds.has(component.id)) problems.push(`${where}: duplicate component id "${component.id}"`);
          componentIds.add(component.id);
        }
      });
      if (asset.components.length === 0 && asset.sourceType !== ASSET_SOURCE_TYPE.PROCEDURAL) {
        problems.push(`${where}: a ${asset.sourceType} asset must list the components it is composed of`);
      }
    }

    // Licence — the record must be complete; whether it *passes* is the gate's business.
    if (!isObject(asset.license)) problems.push(`${where}: license is missing`);
    else {
      const license = asset.license;
      for (const field of ['spdx', 'url', 'attribution', 'decisionNote']) {
        if (!nonEmpty(license[field])) problems.push(`${where}: license.${field} is missing`);
      }
      for (const field of ['redistribution', 'commercialUse']) {
        if (!LICENSE_DECISION_IDS.includes(license[field])) {
          problems.push(`${where}: license.${field} must be one of ${LICENSE_DECISION_IDS.join(' | ')}`);
        }
      }
      if (!ASSESSMENT_BASIS_IDS.includes(license.assessment)) {
        problems.push(`${where}: license.assessment must be one of ${ASSESSMENT_BASIS_IDS.join(' | ')}`);
      }
      if (!DATE_PATTERN.test(license.assessedAt ?? '')) problems.push(`${where}: license.assessedAt must be an ISO date`);
      if (license.decisionRecord !== null && !isRepositoryPath(license.decisionRecord)) {
        problems.push(`${where}: license.decisionRecord must be a repository path or null`);
      }
      if (!Array.isArray(license.obligations)) problems.push(`${where}: license.obligations must be a list`);
      else {
        const obligationIds = new Set();
        license.obligations.forEach((obligation, i) => {
          const at = `license.obligations[${i}]`;
          if (!isObject(obligation)) {
            problems.push(`${where}: ${at} is not an object`);
            return;
          }
          if (!nonEmpty(obligation.id)) problems.push(`${where}: ${at}.id is missing`);
          else if (obligationIds.has(obligation.id)) problems.push(`${where}: duplicate obligation id "${obligation.id}"`);
          else obligationIds.add(obligation.id);
          if (!OBLIGATION_KIND_IDS.includes(obligation.kind)) problems.push(`${where}: ${at}.kind must be one of ${OBLIGATION_KIND_IDS.join(' | ')}`);
          if (!OBLIGATION_STATUS_IDS.includes(obligation.status)) problems.push(`${where}: ${at}.status must be one of ${OBLIGATION_STATUS_IDS.join(' | ')}`);
          for (const field of ['requirement', 'displayedVia']) {
            if (!nonEmpty(obligation[field])) problems.push(`${where}: ${at}.${field} is missing`);
          }
          if (!isStringList(obligation.components) || obligation.components.length === 0) {
            problems.push(`${where}: ${at}.components must name the components it comes from`);
          } else {
            for (const id of obligation.components) {
              if (!componentIds.has(id)) problems.push(`${where}: ${at} names component "${id}", which is not listed`);
            }
          }
          if (obligation.satisfiedBy !== null && !isRepositoryPath(obligation.satisfiedBy)) {
            problems.push(`${where}: ${at}.satisfiedBy must be a repository path or null`);
          }
          if (obligation.status === OBLIGATION_STATUS.SATISFIED && obligation.satisfiedBy === null) {
            problems.push(`${where}: ${at} is satisfied by nothing`);
          }
        });
        // A ShareAlike component without a share-alike obligation is a term nobody wrote down.
        const shareAlikeComponents = (asset.components ?? []).filter(
          (component) => isObject(component) && /-SA-/i.test(component.license ?? '')
        );
        if (shareAlikeComponents.length > 0 && !license.obligations.some((o) => o?.kind === OBLIGATION_KIND.SHARE_ALIKE)) {
          problems.push(`${where}: has ShareAlike components but no share-alike obligation`);
        }
        if ((asset.components ?? []).length > 0 && !license.obligations.some((o) => o?.kind === OBLIGATION_KIND.ATTRIBUTION)) {
          problems.push(`${where}: has components but no attribution obligation`);
        }
      }
    }

    // Files
    if (!Array.isArray(asset.sources) || asset.sources.length === 0) problems.push(`${where}: sources must list every upstream file`);
    else asset.sources.forEach((file, i) => checkFile(problems, where, `sources[${i}]`, file, { allowUrl: true }));
    checkFile(problems, where, 'output', asset.output);
    if (isObject(asset.output) && asset.output.sha256 === null) problems.push(`${where}: output.sha256 is required`);

    // Geometry and semantic parts: meshes only.
    if (asset.kind === ASSET_KIND.MESH) {
      if (!isObject(asset.geometry)) problems.push(`${where}: a mesh asset needs a geometry block`);
      else {
        for (const field of ['coordinateSystem', 'units', 'extent', 'scaleNote']) {
          if (!nonEmpty(asset.geometry[field])) problems.push(`${where}: geometry.${field} is missing`);
        }
      }
      if (!isObject(asset.semanticParts)) problems.push(`${where}: a mesh asset needs a semanticParts block`);
      else {
        if (!nonEmpty(asset.semanticParts.partIdSource)) problems.push(`${where}: semanticParts.partIdSource is missing`);
        if (asset.semanticParts.mappingModule !== null && !isRepositoryPath(asset.semanticParts.mappingModule)) {
          problems.push(`${where}: semanticParts.mappingModule must be a repository path or null`);
        }
        if (asset.semanticParts.partCount !== null && !isCount(asset.semanticParts.partCount)) {
          problems.push(`${where}: semanticParts.partCount must be a non-negative integer or null`);
        }
      }
    } else if (kindKnown) {
      if (asset.geometry != null) problems.push(`${where}: a ${asset.kind} asset has no geometry of its own — drop the geometry block`);
      if (asset.semanticParts != null) problems.push(`${where}: a ${asset.kind} asset has no semantic parts — drop the block`);
    }

    if (!isObject(asset.pipeline)) problems.push(`${where}: pipeline is missing`);
    else {
      if (!isStringList(asset.pipeline.tools)) problems.push(`${where}: pipeline.tools must be a list of tool versions`);
      if (asset.pipeline.generator !== null && !nonEmpty(asset.pipeline.generator)) problems.push(`${where}: pipeline.generator must be a string or null`);
      if (!isStringList(asset.pipeline.steps) || asset.pipeline.steps.length === 0) problems.push(`${where}: pipeline.steps must record the conversion`);
    }
    if (!isStringList(asset.acceptedSimplifications)) problems.push(`${where}: acceptedSimplifications must be a list`);
    if (!isStringList(asset.knownDefects)) problems.push(`${where}: knownDefects must be a list`);

    // Budget
    if (!isObject(asset.budget)) problems.push(`${where}: budget is missing`);
    else {
      for (const field of ['triangles', 'materials', 'textures', 'bytes']) {
        const value = asset.budget[field];
        if (value !== null && !isCount(value)) problems.push(`${where}: budget.${field} must be an integer or null`);
      }
      if (asset.kind === ASSET_KIND.MESH && asset.budget.triangles === null) problems.push(`${where}: a mesh asset must record its triangle count`);
      if (!nonEmpty(asset.budget.targetDevices)) problems.push(`${where}: budget.targetDevices is missing`);
    }

    // QA
    if (!isObject(asset.qa)) problems.push(`${where}: qa is missing`);
    else if (kindKnown) {
      for (const gate of QA_GATE_IDS) checkQaGate(problems, where, asset, gate);
      for (const key of Object.keys(asset.qa)) {
        if (!QA_GATE_IDS.includes(key)) problems.push(`${where}: qa.${key} is not a known gate`);
      }
    }

    // Replacement and release
    if (!isObject(asset.replacement)) problems.push(`${where}: replacement is missing`);
    else {
      if (asset.replacement.replaces !== null && !nonEmpty(asset.replacement.replaces)) problems.push(`${where}: replacement.replaces must be an asset id or null`);
      if (!nonEmpty(asset.replacement.rollback)) problems.push(`${where}: replacement.rollback is missing`);
    }
    if (!isObject(asset.release)) problems.push(`${where}: release is missing`);
    else {
      if (!RELEASE_STATUS_IDS.includes(asset.release.status)) problems.push(`${where}: release.status must be one of ${RELEASE_STATUS_IDS.join(' | ')}`);
      if (!nonEmpty(asset.release.note)) problems.push(`${where}: release.note is missing`);
    }

    // Conditional block for the source type — and none of the others.
    const conditional = CONDITIONAL_FIELDS[asset.sourceType];
    if (conditional) {
      const block = asset[conditional.block];
      if (!isObject(block)) problems.push(`${where}: ${asset.sourceType} requires a "${conditional.block}" block`);
      else {
        for (const field of conditional.fields) {
          const value = block[field];
          const filled = isObject(value) ? Object.keys(value).length > 0 : Array.isArray(value) ? value.length > 0 : nonEmpty(value);
          if (!filled) problems.push(`${where}: ${conditional.block}.${field} is required for ${asset.sourceType}`);
        }
        if (asset.sourceType === ASSET_SOURCE_TYPE.IMAGING_DERIVED) {
          const deid = block.deidentification;
          if (!isObject(deid) || !DEIDENTIFICATION_STATUS_IDS.includes(deid.status)) {
            problems.push(
              `${where}: imaging.deidentification must be an object with status one of ${DEIDENTIFICATION_STATUS_IDS.join(' | ')} — not a sentence`
            );
          } else {
            if (!nonEmpty(deid.method)) problems.push(`${where}: imaging.deidentification.method is missing`);
            if (deid.status === DEIDENTIFICATION_STATUS.CONFIRMED && !isRepositoryPath(deid.reference ?? '')) {
              problems.push(`${where}: imaging.deidentification confirmed without a repository record`);
            }
          }
        }
      }
      for (const [type, other] of Object.entries(CONDITIONAL_FIELDS)) {
        if (type !== asset.sourceType && asset[other.block] != null) {
          problems.push(`${where}: carries a "${other.block}" block that belongs to ${type}, not ${asset.sourceType}`);
        }
      }
    }
  }

  // Replacement targets must exist.
  for (const asset of assets) {
    const target = isObject(asset) ? asset.replacement?.replaces : null;
    if (nonEmpty(target) && !assets.some((other) => isObject(other) && other.assetId === target)) {
      problems.push(`asset "${asset.assetId}": replaces "${target}", which is not in the manifest`);
    }
  }

  return problems;
}

/**
 * Why an asset may not ship to the public product. Empty means it may.
 *
 * Separate from structural validity on purpose: a complete record of an
 * asset whose licence is still being investigated is a good record and a
 * blocked release, and a validator that reported those as one thing would
 * teach people to fill in `allowed` to make the red go away.
 *
 * The gate is closed by default. A gate that applies and is not `passed`
 * blocks; `failed` blocks at every scene status; only the two review gates in
 * `REVIEW_GATES_DEFERRABLE_AT_ALPHA` may be `pending` for an `alpha` scene,
 * because alpha is the status that *means* the review has not happened yet.
 *
 * @param {AssetManifestEntry} asset
 * @param {object} [options]
 * @param {string} [options.sceneStatus] status of the referencing scene; omitted means "treat as reviewed"
 * @param {(path: string) => boolean} [options.fileExists] whether a repository path exists; omitted skips that check
 */
export function assetReleaseProblems(asset, { sceneStatus, fileExists } = {}) {
  const problems = [];
  const where = `asset "${isObject(asset) && nonEmpty(asset.assetId) ? asset.assetId : '(no id)'}"`;
  if (!isObject(asset)) return [`${where}: not an asset record`];

  const license = isObject(asset.license) ? asset.license : {};
  const exists = (path) => (fileExists ? fileExists(path) : true);

  if (license.redistribution !== LICENSE_DECISION.ALLOWED) {
    problems.push(`${where}: redistribution is "${license.redistribution}", not allowed`);
  }
  if (license.commercialUse !== LICENSE_DECISION.ALLOWED) {
    problems.push(`${where}: commercial use is "${license.commercialUse}", not allowed`);
  }
  if (!isRepositoryPath(license.decisionRecord ?? '')) problems.push(`${where}: the licence decision has no record`);
  else if (!exists(license.decisionRecord)) problems.push(`${where}: licence decision record "${license.decisionRecord}" does not exist`);

  for (const obligation of Array.isArray(license.obligations) ? license.obligations : []) {
    const id = isObject(obligation) ? obligation.id : '(malformed)';
    if (!isObject(obligation) || obligation.status !== OBLIGATION_STATUS.SATISFIED) {
      problems.push(`${where}: licence obligation "${id}" is not satisfied`);
      continue;
    }
    if (!isRepositoryPath(obligation.satisfiedBy ?? '')) problems.push(`${where}: licence obligation "${id}" names no record`);
    else if (!exists(obligation.satisfiedBy)) problems.push(`${where}: licence obligation "${id}" points at "${obligation.satisfiedBy}", which does not exist`);
  }

  const outputHash = asset.output?.sha256;
  if (!SHA256_PATTERN.test(outputHash ?? '')) problems.push(`${where}: output hash is not recorded`);
  for (const [i, file] of (Array.isArray(asset.sources) ? asset.sources : []).entries()) {
    if (!SHA256_PATTERN.test(file?.sha256 ?? '')) problems.push(`${where}: sources[${i}] has no recorded hash`);
  }

  const awaitingReview = STATUSES_AWAITING_REVIEW.has(sceneStatus);
  for (const gate of QA_APPLIES[asset.kind] ?? QA_GATE_IDS) {
    const entry = asset.qa?.[gate];
    const status = isObject(entry) ? entry.status : undefined;
    if (status === QA_STATUS.FAILED) {
      problems.push(`${where}: ${gate} failed`);
      continue;
    }
    if (status === QA_STATUS.PENDING && awaitingReview && REVIEW_GATES_DEFERRABLE_AT_ALPHA.includes(gate)) continue;
    if (status !== QA_STATUS.PASSED) {
      problems.push(`${where}: ${gate} is ${status ?? 'not recorded'}, not passed`);
      continue;
    }
    if (HASH_BOUND_GATES.includes(gate) && entry.assetSha256 !== outputHash) {
      problems.push(`${where}: ${gate} was run against a different file (${entry.assetSha256 ?? 'no hash'}), not the current one`);
    }
    if (gate === QA_GATE.FORMAT_VALIDATION && (entry.errors !== 0 || entry.warnings !== 0)) {
      problems.push(`${where}: formatValidation has ${entry.errors} errors and ${entry.warnings} warnings`);
    }
    if (nonEmpty(entry.reference) && !exists(entry.reference)) {
      problems.push(`${where}: ${gate} reference "${entry.reference}" does not exist`);
    }
  }

  if (asset.sourceType === ASSET_SOURCE_TYPE.IMAGING_DERIVED) {
    const deid = asset.imaging?.deidentification;
    if (!isObject(deid) || deid.status !== DEIDENTIFICATION_STATUS.CONFIRMED) {
      problems.push(`${where}: de-identification of the imaging is not confirmed`);
    }
  }

  if (asset.release?.status !== RELEASE_STATUS.RELEASED) {
    problems.push(`${where}: release status is "${asset.release?.status}", not released`);
  }
  return problems;
}

/** @param {AssetManifestEntry} asset */
export const assetIsReleasable = (asset, options) => assetReleaseProblems(asset, options).length === 0;
