/**
 * The scene manifest — the one place a scene is declared to exist.
 *
 * Routing, the scene switcher, the organ explorer and the tests all read this
 * list. Adding a scene is one entry here plus one folder; nothing else in the
 * app has to be touched, which is what keeps a hundred-scene catalogue from
 * turning into a hundred hand-maintained routes.
 *
 * `load` is a dynamic import so that a scene's Three.js code is downloaded only
 * when that scene is opened. Keep the import specifier a literal — a computed
 * path defeats Vite's code splitting and pulls every organ into one bundle.
 *
 * Fields
 *  id           stable, appears in the URL (`#/<slug>`). Never change a published one.
 *  slug         route segment; equal to `id` unless a scene is ever renamed.
 *  system/organ where it sits in `taxonomy.js`. `organs` lists every organ shown.
 *  disease      the disease it is about, or null for normal physiology.
 *  status       prototype | alpha | reviewed | production (see taxonomy.js)
 *  modelCard    repository-relative model card path for alpha/reviewed scenes
 *  load         () => import('...') returning a module whose default export is the scene class
 */
export const SCENE_MANIFEST = [
  {
    id: 'brain-anatomy',
    slug: 'brain-anatomy',
    titleEn: 'Interactive brain anatomy',
    titleJa: '触れて学ぶ脳の解剖',
    system: 'nervous',
    organ: 'brain',
    disease: null,
    status: 'prototype',
    description: 'Select cortical lobes and open the hemispheres to inspect the insula and deep structures.',
    descriptionJa: '大脳各葉を選択し、左右半球を展開して島皮質と深部構造を観察します。',
    tags: ['anatomy', 'interactive', 'cortex'],
    load: () => import('../scenes/nervous/scenes/brainAnatomy/index.js'),
  },
  {
    id: 'amyloid-beta',
    slug: 'amyloid-beta',
    titleEn: 'Amyloid-β',
    titleJa: 'アミロイドβ',
    system: 'nervous',
    organ: 'brain',
    disease: 'alzheimers',
    status: 'production',
    description: 'Aβ monomer → oligomer → fibril → plaque, as one continuous aggregation state.',
    descriptionJa: 'Aβ のモノマー → オリゴマー → 線維 → プラークを、連続した凝集状態として示します。',
    tags: ['molecular', 'aggregation', 'neurodegeneration'],
    load: () => import('../scenes/nervous/scenes/amyloidBeta/index.js'),
  },
  {
    id: 'heart-failure',
    slug: 'heart-failure',
    titleEn: 'Heart failure',
    titleJa: '心不全',
    system: 'cardiovascular',
    organ: 'heart',
    disease: 'heart-failure',
    status: 'production',
    description:
      'Closed-loop time-varying elastance: remodelling, the PV loop and the pressure waveform from one model.',
    descriptionJa:
      '時変エラスタンスの閉ループ循環モデル。リモデリング・PV ループ・圧波形がすべて同じモデルから導かれます。',
    tags: ['haemodynamics', 'reference-implementation', 'learning-module'],
    load: () => import('../scenes/cardiovascular/scenes/heartFailure/index.js'),
  },
  {
    id: 'copd-hyperinflation',
    slug: 'copd',
    titleEn: 'COPD',
    titleJa: 'COPD',
    system: 'respiratory',
    organ: 'lungs',
    organs: ['lungs', 'airway'],
    disease: 'copd',
    status: 'alpha',
    modelCard: 'docs/model-cards/copd.md',
    description:
      'Twelve lung units with their own time constants: why incomplete expiration produces dynamic hyperinflation, and why extra expiratory effort stops increasing flow once expiratory flow limitation is reached.',
    descriptionJa:
      '固有の時定数をもつ 12 単位の肺モデル。呼気が時間内に終わらず動的過膨張が生じる理由と、呼気流量制限に達すると呼気努力を強めても流量を増やせなくなる理由を示します。',
    tags: ['respiratory-mechanics', 'flow-limitation', 'learning-module'],
    load: () => import('../scenes/respiratory/scenes/copd/index.js'),
  },
  {
    id: 'asthma-heterogeneity',
    slug: 'asthma',
    titleEn: 'Asthma',
    titleJa: '喘息',
    system: 'respiratory',
    organ: 'lungs',
    organs: ['lungs', 'airway'],
    disease: 'asthma',
    status: 'alpha',
    modelCard: 'docs/model-cards/asthma.md',
    description:
      'A branching airway tree solved as a network: how a uniform bronchoconstrictor stimulus can produce clustered, heterogeneous regional ventilation.',
    descriptionJa:
      '分岐気道をネットワークとして解き、均一な気管支収縮刺激から不均一で集簇した換気低下が生じる仕組みを示します。',
    tags: ['respiratory-mechanics', 'ventilation-heterogeneity', 'learning-module'],
    load: () => import('../scenes/respiratory/scenes/asthma/index.js'),
  },
  {
    id: 'breathing-lungs',
    slug: 'breathing-lungs',
    titleEn: 'Breathing lungs',
    titleJa: '呼吸と肺',
    system: 'respiratory',
    organ: 'lungs',
    organs: ['lungs', 'airway'],
    disease: null,
    status: 'prototype',
    description: 'Trachea, main bronchi and both lungs expanding and recoiling through the breathing cycle.',
    descriptionJa: '気管・主気管支・両肺が呼吸周期にあわせて膨らみ、縮む様子を示します。',
    tags: ['ventilation', 'cycle'],
    load: () => import('../scenes/respiratory/scenes/breathingLungs/index.js'),
  },
  {
    id: 'upper-gi-peristalsis',
    slug: 'upper-gi-peristalsis',
    titleEn: 'Swallow & gastric mixing',
    titleJa: '嚥下と胃の蠕動',
    system: 'gastrointestinal',
    organ: 'stomach',
    organs: ['esophagus', 'stomach'],
    disease: null,
    status: 'prototype',
    description: 'A constriction wave travelling down the esophagus and around the gastric body.',
    descriptionJa: '食道を下行し、胃体部を回る収縮波（蠕動）を示します。',
    tags: ['peristalsis', 'wave'],
    load: () => import('../scenes/gastrointestinal/scenes/upperGi/index.js'),
  },
  {
    id: 'intestinal-transit',
    slug: 'intestinal-transit',
    titleEn: 'Intestinal transit',
    titleJa: '腸管の輸送',
    system: 'gastrointestinal',
    organ: 'small-intestine',
    organs: ['small-intestine', 'colon'],
    disease: null,
    status: 'prototype',
    description: 'Segmentation giving way to propulsive peristalsis along the small bowel and colon.',
    descriptionJa: '小腸の分節運動から、大腸へ向かう推進性蠕動へと移る動きを示します。',
    tags: ['peristalsis', 'transit'],
    load: () => import('../scenes/gastrointestinal/scenes/intestinalTransit/index.js'),
  },
  {
    id: 'portal-hypertension',
    slug: 'portal-hypertension',
    titleEn: 'Cirrhosis and portal hypertension',
    titleJa: '肝硬変と門脈圧亢進症',
    system: 'hepatobiliary',
    organ: 'liver',
    organs: ['liver', 'spleen'],
    disease: 'cirrhosis',
    status: 'alpha',
    modelCard: 'docs/model-cards/cirrhosis-portal-hypertension.md',
    description:
      'The portal circulation as a flow-conserving network: why portal hypertension can persist despite redistribution through collaterals, and why HVPG is not the portal pressure gradient.',
    descriptionJa:
      '流量保存が成り立つネットワークとして門脈循環を表現し、側副血行路へ血流が再分配されても門脈圧亢進が持続し得る理由と、HVPG が門脈圧較差そのものではない理由を示します。',
    tags: ['haemodynamics', 'portal-hypertension', 'learning-module'],
    load: () => import('../scenes/hepatobiliary/scenes/portalHypertension/index.js'),
  },
  {
    id: 'hepatorenal-syndrome',
    slug: 'hepatorenal-syndrome',
    titleEn: 'Hepatorenal syndrome — the haemodynamic mechanism',
    titleJa: '肝腎症候群（HRS-AKI）― 循環からみる腎機能低下',
    system: 'renal',
    organ: 'kidney',
    organs: ['kidney', 'liver'],
    disease: 'hepatorenal-syndrome',
    status: 'alpha',
    modelCard: 'docs/model-cards/hepatorenal-syndrome.md',
    description:
      'Two organs solved as one circulation. It isolates the haemodynamic and neurohumoral component of HRS-AKI — how far the circulation alone can take glomerular filtration — and models no kidney injury, which is a boundary of the model rather than a claim about the syndrome.',
    descriptionJa:
      '2 つの臓器を 1 つの循環として解き、HRS-AKI のうち循環・神経体液性の機序を分離して、循環だけで糸球体濾過量がどこまで低下し得るかを示します。腎障害は実装していませんが、これはモデルの境界であって症候群についての主張ではありません。',
    tags: ['haemodynamics', 'cross-organ', 'treatment-mechanism'],
    load: () => import('../scenes/renal/scenes/hepatorenalSyndrome/index.js'),
  },
  {
    id: 'liver-portal-flow',
    slug: 'liver-portal-flow',
    titleEn: 'Portal flow & bile',
    titleJa: '門脈血流と胆汁',
    system: 'hepatobiliary',
    organ: 'liver',
    organs: ['liver', 'gallbladder'],
    disease: null,
    status: 'prototype',
    description: 'Portal inflow crossing the lobes to the hepatic veins, and the gallbladder emptying.',
    descriptionJa: '門脈から流入した血液が肝葉を通り肝静脈へ抜ける流れと、胆嚢の収縮を示します。',
    tags: ['flow', 'particles'],
    load: () => import('../scenes/hepatobiliary/scenes/liverPortalFlow/index.js'),
  },
  {
    id: 'pancreatic-secretion',
    slug: 'pancreatic-secretion',
    titleEn: 'Pancreatic secretion',
    titleJa: '膵臓の分泌',
    system: 'hepatobiliary',
    organ: 'pancreas',
    disease: null,
    status: 'prototype',
    description: 'The two outputs of one gland: enzymes into the duct, insulin into the blood.',
    descriptionJa: '1 つの臓器がもつ 2 つの分泌 — 膵管への外分泌と、血中への内分泌を示します。',
    tags: ['secretion', 'endocrine', 'exocrine'],
    load: () => import('../scenes/hepatobiliary/scenes/pancreaticSecretion/index.js'),
  },
  {
    id: 'urinary-filtration',
    slug: 'urinary-filtration',
    titleEn: 'Filtration to bladder',
    titleJa: '濾過から膀胱まで',
    system: 'renal',
    organ: 'kidney',
    organs: ['kidney', 'ureter', 'bladder'],
    disease: null,
    status: 'prototype',
    description: 'Filtrate leaving the kidneys, travelling the ureters, and the bladder filling.',
    descriptionJa: '腎で濾過された尿が尿管を下り、膀胱が充満していく流れを示します。',
    tags: ['flow', 'filling'],
    load: () => import('../scenes/renal/scenes/urinaryFiltration/index.js'),
  },
  {
    id: 'thyroid-hormone',
    slug: 'thyroid-hormone',
    titleEn: 'Thyroid hormone release',
    titleJa: '甲状腺ホルモンの放出',
    system: 'endocrine',
    organ: 'thyroid',
    disease: null,
    status: 'prototype',
    description: 'Follicles releasing hormone into the surrounding capillaries as stimulation rises.',
    descriptionJa: '刺激の増加にあわせ、濾胞から周囲の毛細血管へホルモンが放出される様子を示します。',
    tags: ['secretion', 'particles'],
    load: () => import('../scenes/endocrine/scenes/thyroidHormone/index.js'),
  },
  {
    id: 'adrenal-response',
    slug: 'adrenal-response',
    titleEn: 'Adrenal response',
    titleJa: '副腎の反応',
    system: 'endocrine',
    organ: 'adrenal',
    disease: null,
    status: 'prototype',
    description: 'Cortex and medulla as two layers with two different release time-courses.',
    descriptionJa: '皮質と髄質という 2 層が、異なる時間経過で分泌する様子を示します。',
    tags: ['secretion', 'layers'],
    load: () => import('../scenes/endocrine/scenes/adrenalResponse/index.js'),
  },
  {
    id: 'spleen-filtration',
    slug: 'spleen-filtration',
    titleEn: 'Splenic filtration',
    titleJa: '脾臓での血球処理',
    system: 'hematologic',
    organ: 'spleen',
    disease: null,
    status: 'prototype',
    description: 'Red cells crossing the red pulp; aged cells retained rather than returned.',
    descriptionJa: '赤脾髄を通過する赤血球のうち、老化した赤血球が捕捉される様子を示します。',
    tags: ['flow', 'particles'],
    load: () => import('../scenes/hematologic/scenes/spleenFiltration/index.js'),
  },
  {
    id: 'bone-remodeling',
    slug: 'bone-remodeling',
    titleEn: 'Bone remodelling',
    titleJa: '骨のリモデリング',
    system: 'musculoskeletal',
    organ: 'bone',
    disease: null,
    status: 'prototype',
    description: 'Resorption and formation as two opposing particle streams on one cortical surface.',
    descriptionJa: '皮質骨の表面で、吸収と形成が拮抗する 2 つの流れとして示します。',
    tags: ['turnover', 'particles'],
    load: () => import('../scenes/musculoskeletal/scenes/boneRemodeling/index.js'),
  },
  {
    id: 'muscle-contraction',
    slug: 'muscle-contraction',
    titleEn: 'Muscle contraction',
    titleJa: '骨格筋の収縮',
    system: 'musculoskeletal',
    organ: 'skeletal-muscle',
    disease: null,
    status: 'prototype',
    description: 'A muscle belly shortening and thickening between its tendons as recruitment rises.',
    descriptionJa: '動員が増えるにつれ、腱の間で筋腹が短縮し太くなる様子を示します。',
    tags: ['contraction', 'recruitment'],
    load: () => import('../scenes/musculoskeletal/scenes/muscleContraction/index.js'),
  },
  {
    id: 'uterine-cycle',
    slug: 'uterine-cycle',
    titleEn: 'Endometrial cycle',
    titleJa: '子宮内膜の周期',
    system: 'reproductive',
    organ: 'uterus',
    disease: null,
    status: 'prototype',
    description: 'Endometrial thickness across one cycle, in section.',
    descriptionJa: '1 周期を通じた子宮内膜の厚さの変化を、断面で示します。',
    tags: ['cycle', 'section'],
    load: () => import('../scenes/reproductive/scenes/uterineCycle/index.js'),
  },
  {
    id: 'prostate-outflow',
    slug: 'prostate-outflow',
    titleEn: 'Prostate & outflow',
    titleJa: '前立腺と尿流',
    system: 'reproductive',
    organ: 'prostate',
    disease: null,
    status: 'prototype',
    description: 'Prostatic volume against the calibre of the urethra running through it.',
    descriptionJa: '前立腺の体積と、その中を通る尿道の内径の関係を示します。',
    tags: ['obstruction', 'flow'],
    load: () => import('../scenes/reproductive/scenes/prostateOutflow/index.js'),
  },
  {
    id: 'body-overview',
    slug: 'body-overview',
    titleEn: 'Human body overview',
    titleJa: '全身の概観',
    system: 'systemic',
    organ: 'whole-body',
    organs: [
      'whole-body',
      'brain',
      'heart',
      'lungs',
      'liver',
      'stomach',
      'kidney',
      'small-intestine',
      'colon',
      'bladder',
    ],
    disease: null,
    status: 'prototype',
    description: 'Where the organ scenes sit relative to one another, built from the same organ builders.',
    descriptionJa: '各臓器シーンの位置関係を、同じ臓器ジオメトリを再利用して 1 つのビューに示します。',
    tags: ['overview', 'orientation'],
    load: () => import('../scenes/systemic/scenes/bodyOverview/index.js'),
  },
];

/**
 * Disease scenes this architecture exists for, none of them built yet.
 *
 * They are listed — not implemented — so that the explorer shows the direction
 * and so that the split between "the organ" and "what is wrong with it" is
 * visible before the second scene of an organ arrives. Moving one of these into
 * `SCENE_MANIFEST` is the whole ceremony of adding a disease scene.
 */
export const PLANNED_SCENES = [
  { organ: 'lungs', disease: 'pneumonia', titleEn: 'Pneumonia', titleJa: '肺炎' },
  { organ: 'lungs', disease: 'pulmonary-edema', titleEn: 'Pulmonary oedema', titleJa: '肺水腫' },
  { organ: 'kidney', disease: 'ckd', titleEn: 'Chronic kidney disease', titleJa: '慢性腎臓病' },
  { organ: 'kidney', disease: 'aki', titleEn: 'Acute kidney injury', titleJa: '急性腎障害' },
  { organ: 'kidney', disease: 'nephrotic-syndrome', titleEn: 'Nephrotic syndrome', titleJa: 'ネフローゼ症候群' },
  { organ: 'liver', disease: 'steatosis', titleEn: 'Steatosis', titleJa: '脂肪肝' },
  { organ: 'liver', disease: 'hepatitis', titleEn: 'Hepatitis', titleJa: '肝炎' },
  { organ: 'brain', disease: 'stroke', titleEn: 'Stroke', titleJa: '脳梗塞' },
  { organ: 'brain', disease: 'parkinsons', titleEn: "Parkinson's disease", titleJa: 'パーキンソン病' },
  { organ: 'heart', disease: 'valve-disease', titleEn: 'Valve disease', titleJa: '弁膜症' },
  { organ: 'heart', disease: 'ischemia', titleEn: 'Myocardial ischaemia', titleJa: '心筋虚血' },
];
