/**
 * The scene manifest — the one place a scene is declared to exist.
 *
 * Routing, the scene switcher, the organ explorer and the tests all read this
 * list. Adding a scene is one entry here plus one folder; nothing else in the
 * app has to be touched, which is what keeps a hundred-scene catalogue from
 * turning into a hundred hand-maintained routes.
 *
 * `load` is a dynamic import so that a scene's Three.js code is downloaded only
 * when that scene is opened. Keep the import specifier a literal — a computed
 * path defeats Vite's code splitting and pulls every organ into one bundle.
 *
 * Fields
 *  id           stable, appears in the URL (`#/<slug>`). Never change a published one.
 *  slug         route segment; equal to `id` unless a scene is ever renamed.
 *  system/organ where it sits in `taxonomy.js`. `organs` lists every organ shown.
 *  disease      the disease it is about, or null for normal physiology.
 *  status       prototype | alpha | reviewed | production (see taxonomy.js)
 *  access       optional paid professional-use surfaces; omitted means free-only
 *  modelCard    repository-relative model card path for alpha/reviewed scenes
 *  modelProfile id of the release profile in `modelProfiles.js` — what kind of claim the
 *               scene makes (geometry basis, mechanism level, personalization, intended and
 *               prohibited uses). Required above prototype; it carries no medical text
 *  load         () => import('...') returning a module whose default export is the scene class
 */
export const SCENE_MANIFEST = [
  {
    id: 'brain-anatomy',
    slug: 'brain-anatomy',
    titleEn: 'Interactive brain anatomy',
    titleJa: '触れて学ぶ脳の解剖',
    system: 'nervous',
    organ: 'brain',
    disease: null,
    conditions: ['brain anatomy', 'gyri and sulci', '脳解剖'],
    status: 'alpha',
    modelCard: 'docs/model-cards/brain-anatomy.md',
    modelProfile: 'brain-anatomy-reference-atlas',
    description: 'Select individual gyri and sulci, peel back an operculum and reveal deep structures in place.',
    descriptionJa: '脳回・脳溝を個別に選択し、弁蓋部を薄くして島皮質と深部構造を本来の位置で観察します。',
    tags: ['anatomy', 'interactive', 'cortex'],
    /**
     * Where else this subject is shown — declared here rather than on the
     * scene's metadata, and that is deliberate.
     *
     * `src/data/brainAnatomy.js` is a pinned model source: touching it moves the
     * card revision, which makes the beta's publication decision stale, which
     * closes the one scene the beta publishes. Which scenes relate to which is
     * catalogue information anyway, so it lives with the catalogue and nothing
     * about the model changes.
     *
     * **The note does a second job here.** The heart's links go between models
     * of one organ at one scale. This one crosses scales: the amyloid scene is
     * a schematic of molecules around a single neuron, with no anatomical scale
     * and no location inside this brain. Moving to it is a change of subject and
     * **not a zoom**, and implying otherwise — that pushing in on a gyrus would
     * reveal those particles — is the misreading this exists to prevent.
     */
    related: {
      scenes: [
        {
          slug: 'amyloid-beta',
          // Not a zoom: see `src/data/relatedContract.js`. The prose note below
          // says why; this is the same thing in a form the panel can act on.
          transitionType: 'scale-change',
          scaleRelationship: 'schematic',
          label: 'Amyloid-β — a schematic at a different scale',
          labelJa: 'アミロイドβ — 別のスケールの模式図',
          why: 'Molecules around a single neuron, drawn as a diagram. **Not a zoom into this brain**: it has no anatomical scale and no place inside it.',
          whyJa: '1 個の神経細胞のまわりの分子を図として描いたものです。**この脳を拡大したものではありません**——解剖学的な縮尺も、この脳の中での位置も持ちません。',
        },
      ],
      note:
        '**A different model, and a different scale.** This atlas is gross anatomy: nothing smaller '
        + 'than a named structure is drawn. The amyloid scene is a schematic of molecular species '
        + 'around one neuron, at no anatomical scale. Moving between them is a change of subject, '
        + '**not a zoom**, and neither model says where in this brain those particles would be.',
      noteJa:
        '**別のモデルで、別のスケールです。** このアトラスは肉眼解剖で、名前の付いた構造より小さい'
        + 'ものは描いていません。アミロイドβのシーンは 1 個の神経細胞のまわりの分子種の模式図で、'
        + '解剖学的な縮尺を持ちません。行き来は主題の切り替えであって**拡大ではなく**、この脳の'
        + 'どこにその粒があるのかは、どちらのモデルも述べていません。',
    },
    load: () => import('../scenes/nervous/scenes/brainAnatomy/index.js'),
  },
  {
    id: 'amyloid-beta',
    slug: 'amyloid-beta',
    titleEn: 'Alzheimer disease: amyloid-β aggregation',
    titleJa: 'Alzheimer病：アミロイドβ凝集',
    storyTitleEn: 'Amyloid-β',
    storyTitleJa: 'アミロイドβ',
    system: 'nervous',
    organ: 'brain',
    disease: 'alzheimers',
    conditions: ['Alzheimer disease', 'AD', 'amyloid-beta aggregation', 'アルツハイマー病', '認知症'],
    uses: ['patient', 'education'],
    status: 'production',
    access: { patient: true, education: true },
    modelProfile: 'amyloid-beta-aggregation-illustration',
    description: 'Aβ monomer → oligomer → fibril → plaque, as one continuous aggregation state.',
    descriptionJa: 'Aβ のモノマー → オリゴマー → 線維 → プラークを、連続した凝集状態として示します。',
    tags: ['molecular', 'aggregation', 'neurodegeneration'],
    load: () => import('../scenes/nervous/scenes/amyloidBeta/index.js'),
  },
  {
    id: 'heart-anatomy',
    slug: 'heart-anatomy',
    titleEn: 'Interactive heart anatomy',
    titleJa: '触れて学ぶ心臓の解剖',
    system: 'cardiovascular',
    organ: 'heart',
    disease: null,
    conditions: ['heart anatomy', 'cardiac chambers', 'heart valves', '心臓解剖', '心腔', '心臓弁'],
    status: 'alpha',
    modelCard: 'docs/model-cards/heart-anatomy.md',
    modelProfile: 'heart-anatomy-reference-atlas',
    description: 'The four chambers, the septum, the four valves and the papillary muscles, each selectable by name.',
    descriptionJa: '四腔・心室中隔・4 つの弁・乳頭筋を、名前で個別に選択できます。',
    tags: ['anatomy', 'interactive', 'chambers'],
    load: () => import('../scenes/cardiovascular/scenes/heartAnatomy/index.js'),
  },
  {
    id: 'heart-failure',
    slug: 'heart-failure',
    titleEn: 'Heart failure',
    titleJa: '心不全',
    system: 'cardiovascular',
    organ: 'heart',
    disease: 'heart-failure',
    conditions: ['heart failure', 'HF', 'HFrEF', '心不全', '左室収縮不全'],
    uses: ['patient', 'education', 'clinical-learning'],
    status: 'production',
    access: { patient: true, education: true },
    modelProfile: 'heart-failure-elastance-loop',
    description:
      'Closed-loop time-varying elastance: remodelling, the PV loop and the pressure waveform from one model.',
    descriptionJa:
      '時変エラスタンスの閉ループ循環モデル。リモデリング・PV ループ・圧波形がすべて同じモデルから導かれます。',
    tags: ['haemodynamics', 'reference-implementation', 'learning-module'],
    load: () => import('../scenes/cardiovascular/scenes/heartFailure/index.js'),
  },
  {
    id: 'circulation',
    slug: 'circulation',
    titleEn: 'Low cardiac output and oxygen delivery',
    titleJa: '低心拍出量と酸素供給',
    storyTitleEn: 'Is circulation maintained?',
    storyTitleJa: '循環、保たれてる？',
    system: 'cardiovascular',
    organ: 'heart',
    disease: 'low-cardiac-output',
    conditions: ['low cardiac output', 'oxygen delivery', 'DO2', '低心拍出', '酸素供給', 'ショック'],
    uses: ['education', 'clinical-learning'],
    status: 'alpha',
    modelCard: 'docs/model-cards/circulation.md',
    modelProfile: 'circulation-steady-state-lumped',
    description:
      'One constructed low-output case with MAP 70: choose baseline, a fluid-responsive state or a dobutamine state and compare pressure, flow and calculated global oxygen delivery.',
    descriptionJa:
      'MAP 70の低拍出概念症例。基準・輸液反応・ドブタミン（DOB）反応から1つを選び、血圧・血流・計算上のglobal DO₂を比較します。',
    tags: ['haemodynamics', 'oxygen-delivery', 'tactile-interaction'],
    load: () => import('../scenes/cardiovascular/scenes/circulation/index.js'),
  },
  {
    id: 'lung-anatomy',
    slug: 'lung-anatomy',
    titleEn: 'Interactive lung anatomy',
    titleJa: '触れて学ぶ肺の解剖',
    system: 'respiratory',
    organ: 'lungs',
    organs: ['lungs', 'airway'],
    disease: null,
    conditions: ['lung anatomy', 'pulmonary lobes', 'bronchopulmonary segments', '肺解剖', '肺葉', '肺区域'],
    status: 'alpha',
    modelCard: 'docs/model-cards/lung-anatomy.md',
    modelProfile: 'lung-anatomy-procedural-atlas',
    description:
      'Five lobes, eighteen segmental bronchi with the artery that runs with each, and the veins that run between segments instead — every one of them selectable by name.',
    descriptionJa:
      '5つの肺葉、18本の区域気管支とそれに伴走する区域動脈、そして区域の「間」を走る静脈を、すべて名前で選択できます。',
    tags: ['anatomy', 'interactive', 'segments'],
    relatedScenes: ['copd-hyperinflation'],
    related: {
      scenes: [
        {
          slug: 'copd',
          label: 'COPD — why a full lung cannot empty in time',
          labelJa: 'COPD — 膨らんだ肺が吐ききれなくなるまで',
          why: '**A different model.** Airways and a diaphragm that move with the breath; this atlas does not breathe.',
          whyJa: '**別のモデルです。** 呼吸に合わせて動く気道と横隔膜を持ちます。このアトラスは呼吸しません。',
        },
        {
          slug: 'asthma',
          label: 'Asthma — why the same lung is not narrowed evenly',
          labelJa: '喘息 — 同じ肺のなかで狭くなり方がそろわない',
          why: '**A different model.** The airway tree carries a per-region state; the atlas carries names only.',
          whyJa: '**別のモデルです。** 気道樹が場所ごとの状態を持ちます。アトラスが持つのは名前だけです。',
        },
        {
          slug: 'pulmonary-edema',
          label: 'Pulmonary edema — when pressure pushes fluid into the air spaces',
          labelJa: '肺水腫 — 圧が水分を空気の側へ押し出すとき',
          why: '**A different model.** It solves a pressure and a flooded fraction; neither exists in this atlas.',
          whyJa: '**別のモデルです。** 圧と浸水した割合を解きます。どちらもこのアトラスにはありません。',
        },
        {
          slug: 'pneumonia',
          label: 'Pneumonia — a region that fills and stops taking part',
          labelJa: '肺炎 — 詰まって換気から外れる領域',
          why: '**A different model.** One region is consolidated and shunts; the atlas has no gas exchange at all.',
          whyJa: '**別のモデルです。** 1 つの領域が硬化しシャントします。アトラスにガス交換はありません。',
        },
        {
          slug: 'pulmonary-embolism',
          label: 'Pulmonary embolism — perfusion lost while ventilation stays',
          labelJa: '肺塞栓症 — 換気は残り、血流だけが失われる',
          why: '**A different model.** It separates ventilation from perfusion; this atlas draws neither.',
          whyJa: '**別のモデルです。** 換気と血流を分けて扱います。このアトラスはどちらも描きません。',
        },
      ],
      note:
        '**None of these is this atlas later.** Each is a separate schematic model with its own geometry, built to show a mechanism rather than a specimen. Nothing is deformed, cut or joined to resemble the other, and no measurement crosses between them.',
      noteJa:
        '**どれも「このアトラスのその後」ではありません。** それぞれ独自の形状を持つ別の模式モデルで、標本ではなく仕組みを見せるために作られています。片方をもう片方に似せるための変形・切断・接合はしていませんし、計測値がまたいで使われることもありません。',
    },
    load: () => import('../scenes/respiratory/scenes/lungAnatomy/index.js'),
  },
  {
    id: 'copd-hyperinflation',
    slug: 'copd',
    titleEn: 'COPD',
    titleJa: 'COPD',
    system: 'respiratory',
    organ: 'lungs',
    organs: ['lungs', 'airway'],
    disease: 'copd',
    conditions: ['COPD', 'chronic obstructive pulmonary disease', 'emphysema', 'dynamic hyperinflation', '慢性閉塞性肺疾患', '肺気腫', '動的過膨張'],
    uses: ['patient', 'education', 'clinical-learning'],
    status: 'reviewed',
    access: { patient: true, education: true },
    modelCard: 'docs/model-cards/copd.md',
    modelProfile: 'copd-time-constant-units',
    description:
      'Twelve lung units with their own time constants: why incomplete expiration produces dynamic hyperinflation, and why extra expiratory effort stops increasing flow once expiratory flow limitation is reached.',
    descriptionJa:
      '固有の時定数をもつ 12 単位の肺モデル。呼気が時間内に終わらず動的過膨張が生じる理由と、呼気流量制限に達すると呼気努力を強めても流量を増やせなくなる理由を示します。',
    tags: ['respiratory-mechanics', 'flow-limitation', 'learning-module'],
    relatedScenes: ['lung-anatomy'],
    load: () => import('../scenes/respiratory/scenes/copd/index.js'),
  },
  {
    id: 'asthma-heterogeneity',
    slug: 'asthma',
    titleEn: 'Asthma',
    titleJa: '喘息',
    system: 'respiratory',
    organ: 'lungs',
    organs: ['lungs', 'airway'],
    disease: 'asthma',
    conditions: ['asthma', 'bronchial asthma', 'bronchoconstriction', '気管支喘息', '喘息発作', '気道収縮'],
    uses: ['patient', 'education', 'clinical-learning'],
    status: 'reviewed',
    access: { patient: true, education: true },
    modelCard: 'docs/model-cards/asthma.md',
    modelProfile: 'asthma-airway-network',
    description:
      'A branching airway tree solved as a network: how a uniform bronchoconstrictor stimulus can produce clustered, heterogeneous regional ventilation.',
    descriptionJa:
      '分岐気道をネットワークとして解き、均一な気管支収縮刺激から不均一で集簇した換気低下が生じる仕組みを示します。',
    tags: ['respiratory-mechanics', 'ventilation-heterogeneity', 'learning-module'],
    load: () => import('../scenes/respiratory/scenes/asthma/index.js'),
  },
  {
    id: 'myocardial-ischemia',
    slug: 'myocardial-ischemia',
    titleEn: 'Myocardial ischemia',
    titleJa: '心筋虚血',
    storyTitleEn: 'Which muscle a narrowed artery starves',
    storyTitleJa: '細くなった血管は、どの筋肉を飢えさせるか',
    system: 'cardiovascular',
    organ: 'heart',
    disease: 'myocardial-ischemia',
    conditions: ['myocardial ischemia', 'coronary artery disease', 'angina', 'CAD', '冠動脈疾患', '狭心症'],
    uses: ['education', 'clinical-learning'],
    status: 'alpha',
    modelCard: 'docs/model-cards/myocardial-ischemia.md',
    modelProfile: 'myocardial-ischemia-supply-demand',
    description:
      'A coronary artery does not supply the groove it runs in — it supplies everything downstream. Oxygen debt accumulates before a wall stops moving, and restoring the flow does not restore the contraction.',
    descriptionJa:
      '冠動脈は自分が走る溝を養うのではなく、下流のすべてを養います。壁が動かなくなる前に酸素負債が溜まり、血流を戻しても収縮は戻りません。',
    tags: ['physiology', 'haemodynamics', 'perfusion'],
    load: () => import('../scenes/cardiovascular/scenes/myocardialIschemia/index.js'),
  },
  {
    id: 'pulmonary-edema',
    slug: 'pulmonary-edema',
    titleEn: 'Pulmonary oedema',
    titleJa: '肺水腫',
    storyTitleEn: 'Where the water goes',
    storyTitleJa: '水は、どこへ行くのか',
    system: 'respiratory',
    organ: 'lungs',
    disease: 'pulmonary-edema',
    conditions: ['pulmonary oedema', 'pulmonary edema', 'cardiogenic pulmonary oedema', 'Starling equation', '肺水腫', '心原性肺水腫'],
    uses: ['patient', 'education', 'clinical-learning'],
    status: 'alpha',
    modelCard: 'docs/model-cards/pulmonary-edema.md',
    modelProfile: 'pulmonary-edema-starling-buffers',
    description:
      'One Starling equation across the pulmonary capillary, and the three buffers that decide whether a raised left atrial pressure ends in a wet interstitium or a flooded alveolus.',
    descriptionJa:
      '肺毛細血管を挟んだ 1 つの Starling 式と、上がった左房圧が「湿った間質」で止まるか「水没した肺胞」に至るかを決める 3 つの緩衝機構。',
    tags: ['physiology', 'haemodynamics', 'gas exchange'],
    load: () => import('../scenes/respiratory/scenes/pulmonaryEdema/index.js'),
  },
  {
    id: 'pneumonia-consolidation',
    slug: 'pneumonia',
    titleEn: 'Pneumonia',
    titleJa: '肺炎',
    system: 'respiratory',
    organ: 'lungs',
    disease: 'pneumonia',
    conditions: ['pneumonia', 'community-acquired pneumonia', 'CAP', 'alveolar consolidation', 'intrapulmonary shunt', '市中肺炎', '肺胞性コンソリデーション', '肺内シャント'],
    uses: ['patient', 'education', 'clinical-learning'],
    status: 'alpha',
    modelCard: 'docs/model-cards/pneumonia.md',
    modelProfile: 'pneumonia-consolidation-shunt',
    description:
      'Twelve regional units show the core V/Q mechanism: alveolar consolidation removes ventilation while perfusion persists, creating intrapulmonary shunt.',
    descriptionJa:
      '12領域の肺モデルで、肺胞性コンソリデーションにより換気が失われても灌流が残り、肺内シャントが生じる基本的なV/Q機序を示します。',
    tags: ['gas-exchange', 'consolidation', 'shunt', 'ventilation-perfusion'],
    load: () => import('../scenes/respiratory/scenes/pneumonia/index.js'),
  },
  {
    id: 'pulmonary-embolism',
    slug: 'pulmonary-embolism',
    titleEn: 'Pulmonary embolism',
    titleJa: '肺塞栓症',
    system: 'respiratory',
    organ: 'lungs',
    disease: 'pulmonary-embolism',
    conditions: ['pulmonary embolism', 'PE', 'pulmonary thromboembolism', 'PTE', 'alveolar dead space', 'right ventricular afterload', '肺血栓塞栓症', '肺塞栓', '肺胞死腔', '右室後負荷'],
    uses: ['patient', 'education', 'clinical-learning'],
    status: 'alpha',
    modelCard: 'docs/model-cards/pulmonary-embolism.md',
    modelProfile: 'pulmonary-embolism-dead-space',
    description:
      'Twelve parallel vascular territories show ventilation continuing beyond obstructed perfusion, the resulting dead-space mechanism and rising relative pulmonary vascular load.',
    descriptionJa:
      '12本の並列肺血管領域で、灌流が遮断された先でも換気が続く死腔機序と、相対的な肺血管負荷の上昇を示します。',
    tags: ['gas-exchange', 'dead-space', 'pulmonary-vascular-resistance', 'ventilation-perfusion'],
    load: () => import('../scenes/respiratory/scenes/pulmonaryEmbolism/index.js'),
  },
  {
    id: 'breathing-lungs',
    slug: 'breathing-lungs',
    titleEn: 'Breathing lungs',
    titleJa: '呼吸と肺',
    system: 'respiratory',
    organ: 'lungs',
    organs: ['lungs', 'airway'],
    disease: null,
    status: 'prototype',
    description: 'Trachea, main bronchi and both lungs expanding and recoiling through the breathing cycle.',
    descriptionJa: '気管・主気管支・両肺が呼吸周期にあわせて膨らみ、縮む様子を示します。',
    tags: ['ventilation', 'cycle'],
    load: () => import('../scenes/respiratory/scenes/breathingLungs/index.js'),
  },
  {
    id: 'stomach-anatomy',
    slug: 'stomach-anatomy',
    titleEn: 'Interactive stomach anatomy',
    titleJa: '触れて学ぶ胃の解剖',
    system: 'gastrointestinal',
    organ: 'stomach',
    organs: ['stomach', 'esophagus', 'small-intestine'],
    disease: null,
    conditions: ['stomach anatomy', 'gastric regions', 'pylorus', '胃解剖', '胃底部', '幽門'],
    status: 'alpha',
    modelCard: 'docs/model-cards/stomach-anatomy.md',
    modelProfile: 'stomach-anatomy-procedural-atlas',
    description:
      'Fundus, cardia, body, antrum and pyloric canal as five separate walls, with the sphincter ring at the outlet and the duodenum it opens into.',
    descriptionJa:
      '胃底部・噴門部・胃体部・前庭部・幽門管を5つの別々の壁として表示し、出口の括約筋リングと開口先の十二指腸も示します。',
    tags: ['anatomy', 'interactive', 'upper-gi'],
    relatedScenes: ['upper-gi-peristalsis'],
    load: () => import('../scenes/gastrointestinal/scenes/stomachAnatomy/index.js'),
  },
  {
    id: 'esophagus-anatomy',
    slug: 'esophagus-anatomy',
    titleEn: 'Interactive oesophageal anatomy',
    titleJa: '触れて学ぶ食道の解剖',
    system: 'gastrointestinal',
    organ: 'esophagus',
    organs: ['esophagus'],
    disease: null,
    conditions: ['esophagus anatomy', 'oesophageal constrictions', '食道解剖', '食道狭窄部', '食道裂孔'],
    status: 'alpha',
    modelCard: 'docs/model-cards/esophagus-anatomy.md',
    modelProfile: 'esophagus-anatomy-procedural-atlas',
    description:
      'Cervical, thoracic and abdominal parts, and the three places the tube is narrow \u2014 each narrow for a different reason, with that reason drawn beside it.',
    descriptionJa:
      '頸部・胸部・腹部食道と、3か所の生理的狭窄部を示します。狭くなる理由は3か所それぞれ異なり、その原因となる構造を隣に描いています。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/gastrointestinal/scenes/esophagusAnatomy/index.js'),
  },
  {
    id: 'upper-gi-peristalsis',
    slug: 'upper-gi-peristalsis',
    titleEn: 'Swallow & gastric mixing',
    titleJa: '嚥下と胃の蠕動',
    system: 'gastrointestinal',
    organ: 'stomach',
    organs: ['esophagus', 'stomach'],
    disease: null,
    status: 'prototype',
    description: 'A constriction wave travelling down the esophagus and around the gastric body.',
    descriptionJa: '食道を下行し、胃体部を回る収縮波（蠕動）を示します。',
    tags: ['peristalsis', 'wave'],
    relatedScenes: ['stomach-anatomy'],
    load: () => import('../scenes/gastrointestinal/scenes/upperGi/index.js'),
  },
  {
    id: 'intestine-anatomy',
    slug: 'intestine-anatomy',
    titleEn: 'Interactive intestinal anatomy',
    titleJa: '触れて学ぶ腸の解剖',
    system: 'gastrointestinal',
    organ: 'colon',
    organs: ['colon', 'small-intestine'],
    disease: null,
    conditions: ['intestinal anatomy', 'colon', 'colic flexures', '腸解剖', '結腸', '結腸曲'],
    status: 'alpha',
    modelCard: 'docs/model-cards/intestine-anatomy.md',
    modelProfile: 'intestine-anatomy-procedural-atlas',
    description:
      'Caecum, ascending, transverse, descending and sigmoid as separate parts with the two colic flexures between them, and the small bowel that fills the frame they make.',
    descriptionJa:
      '盲腸・上行・横行・下行・S状結腸を別々の部位として表示し、その間の2つの結腸曲と、枠の内側を満たす小腸も示します。',
    tags: ['anatomy', 'interactive', 'lower-gi'],
    relatedScenes: ['intestinal-transit'],
    load: () => import('../scenes/gastrointestinal/scenes/intestineAnatomy/index.js'),
  },
  {
    id: 'intestinal-transit',
    slug: 'intestinal-transit',
    titleEn: 'Intestinal transit',
    titleJa: '腸管の輸送',
    system: 'gastrointestinal',
    organ: 'small-intestine',
    organs: ['small-intestine', 'colon'],
    disease: null,
    status: 'prototype',
    description: 'Segmentation giving way to propulsive peristalsis along the small bowel and colon.',
    descriptionJa: '小腸の分節運動から、大腸へ向かう推進性蠕動へと移る動きを示します。',
    tags: ['peristalsis', 'transit'],
    relatedScenes: ['intestine-anatomy'],
    load: () => import('../scenes/gastrointestinal/scenes/intestinalTransit/index.js'),
  },
  {
    id: 'liver-anatomy',
    slug: 'liver-anatomy',
    titleEn: 'Interactive liver anatomy',
    titleJa: '触れて学ぶ肝臓の解剖',
    system: 'hepatobiliary',
    organ: 'liver',
    organs: ['liver', 'gallbladder'],
    disease: null,
    conditions: ['liver anatomy', 'Couinaud segments', 'Cantlie line', '肝解剖', '肝区域', 'Couinaud分類'],
    status: 'alpha',
    modelCard: 'docs/model-cards/liver-anatomy.md',
    modelProfile: 'liver-anatomy-procedural-atlas',
    description:
      'Couinaud’s eight segments — nine parts to point at, because IV is carried as IVa and IVb — with the hepatic veins that run between them and the portal pedicles that run inside them.',
    descriptionJa:
      'Couinaudの8区域を、IVをIVa・IVbに分けた9つの部分として選べます。区域の「間」を走る肝静脈と、「内部」を走る門脈枝の違いを示します。',
    tags: ['anatomy', 'interactive', 'segments'],
    relatedScenes: ['portal-hypertension'],
    related: {
      scenes: [
        {
          slug: 'portal-hypertension',
          label: 'Portal hypertension — when the liver is hard to flow through',
          labelJa: '門脈圧亢進症 — 肝臓が流れにくくなるとき',
          why: '**A different model.** A resistance and a pressure the atlas has no place for; its segments are shape, not flow.',
          whyJa: '**別のモデルです。** アトラスが持たない抵抗と圧を解きます。区域は形であって流れではありません。',
        },
        {
          slug: 'hepatorenal-syndrome',
          label: 'Hepatorenal syndrome — the liver read through the kidney',
          labelJa: '肝腎症候群 — 肝臓の変化を腎臓側から読む',
          why: '**A different model, and two organs.** It couples a circulation to a kidney; nothing here is that couple.',
          whyJa: '**別のモデルで、臓器も 2 つです。** 循環と腎臓を連成させます。ここにその連成はありません。',
        },
      ],
      note:
        '**None of these is this atlas later.** Each is a separate schematic model with its own geometry, built to show a mechanism rather than a specimen. Nothing is deformed, cut or joined to resemble the other, and no measurement crosses between them.',
      noteJa:
        '**どれも「このアトラスのその後」ではありません。** それぞれ独自の形状を持つ別の模式モデルで、標本ではなく仕組みを見せるために作られています。片方をもう片方に似せるための変形・切断・接合はしていませんし、計測値がまたいで使われることもありません。',
    },
    load: () => import('../scenes/hepatobiliary/scenes/liverAnatomy/index.js'),
  },
  {
    id: 'portal-hypertension',
    slug: 'portal-hypertension',
    titleEn: 'Cirrhosis and portal hypertension',
    titleJa: '肝硬変と門脈圧亢進症',
    system: 'hepatobiliary',
    organ: 'liver',
    organs: ['liver', 'spleen'],
    disease: 'cirrhosis',
    conditions: ['cirrhosis', 'portal hypertension', 'HVPG', 'varices', '肝硬変', '門脈圧亢進症', '食道静脈瘤'],
    uses: ['patient', 'education', 'clinical-learning'],
    status: 'reviewed',
    access: { patient: true, education: true },
    modelCard: 'docs/model-cards/cirrhosis-portal-hypertension.md',
    modelProfile: 'portal-hypertension-resistance-network',
    description:
      'The portal circulation as a flow-conserving network: why portal hypertension can persist despite redistribution through collaterals, and why HVPG is not the portal pressure gradient.',
    descriptionJa:
      '流量保存が成り立つネットワークとして門脈循環を表現し、側副血行路へ血流が再分配されても門脈圧亢進が持続し得る理由と、HVPG が門脈圧較差そのものではない理由を示します。',
    tags: ['haemodynamics', 'portal-hypertension', 'learning-module'],
    relatedScenes: ['liver-anatomy'],
    load: () => import('../scenes/hepatobiliary/scenes/portalHypertension/index.js'),
  },
  {
    id: 'bowel-obstruction',
    slug: 'bowel-obstruction',
    titleEn: 'Bowel obstruction',
    titleJa: '腸閉塞',
    system: 'gastrointestinal',
    organ: 'small-intestine',
    organs: ['small-intestine', 'colon'],
    disease: 'mechanical-bowel-obstruction',
    conditions: ['bowel obstruction', 'small bowel obstruction', 'large bowel obstruction', 'closed loop obstruction', 'transition point', 'ileocaecal valve', '腸閉塞', 'イレウス', '閉鎖係蹄', '移行部'],
    uses: ['education', 'clinical-learning'],
    status: 'alpha',
    modelCard: 'docs/model-cards/bowel-obstruction.md',
    modelProfile: 'bowel-obstruction-site',
    description:
      'The gut is one path in series, so a blockage divides it: everything above keeps receiving and cannot pass anything on, everything below receives nothing. Where it sits decides how much bowel is above it \u2014 and the wall that carries the most is at neither end.',
    descriptionJa:
      '腸は直列の 1 本の通り道で、閉塞はそれを 2 つに分けます。上流は受け取り続けて送り出せず、下流には何も届きません。部位によって上流の腸の長さが決まり、壁の負担が最大になるのはそのどちらでもありません。',
    tags: ['gastrointestinal', 'obstruction', 'site-scenario'],
    load: () => import('../scenes/gastrointestinal/scenes/bowelObstruction/index.js'),
  },
  {
    id: 'achalasia',
    slug: 'achalasia',
    titleEn: 'Achalasia',
    titleJa: 'アカラシア',
    system: 'gastrointestinal',
    organ: 'esophagus',
    organs: ['esophagus'],
    disease: 'achalasia',
    conditions: ['achalasia', 'oesophageal achalasia', 'esophageal achalasia', 'impaired LES relaxation', 'aperistalsis', 'アカラシア', '食道アカラシア', '下部食道括約筋弛緩不全', '蠕動消失'],
    uses: ['education', 'clinical-learning'],
    status: 'alpha',
    modelCard: 'docs/model-cards/achalasia.md',
    modelProfile: 'achalasia-swallow-transport',
    description:
      'One swallow model: why a wave that stops travelling and a ring that does not let go retain what was swallowed, and why the column that collects is what settles where it stops.',
    descriptionJa:
      '1 つの嚥下モデル。途中で伝わらなくなる波と、緩まない輪が飲み込んだものを貯留させる理由と、溜まった液柱自体が落ち着き先を決める仕組みを示します。',
    tags: ['gastrointestinal', 'motility', 'time-to-balance'],
    load: () => import('../scenes/gastrointestinal/scenes/achalasia/index.js'),
  },
  {
    id: 'benign-prostatic-enlargement',
    slug: 'benign-prostatic-enlargement',
    titleEn: 'Benign prostatic enlargement',
    titleJa: '前立腺肥大',
    system: 'reproductive',
    organ: 'prostate',
    organs: ['prostate', 'bladder'],
    disease: 'benign-prostatic-hyperplasia',
    conditions: ['benign prostatic hyperplasia', 'BPH', 'benign prostatic enlargement', 'transition zone', 'median lobe', '前立腺肥大症', '移行域', '中葉'],
    uses: ['education', 'clinical-learning'],
    status: 'alpha',
    modelCard: 'docs/model-cards/benign-prostatic-enlargement.md',
    modelProfile: 'benign-prostatic-enlargement-zonal',
    description:
      'The transition zone grows and the gland grows far less, because the peripheral zone is not enlarged by it \u2014 it is displaced into a rim, with nothing taken out of it.',
    descriptionJa:
      '大きくなるのは移行域で、腺全体の変化ははるかに小さくなります。末梢域は大きくならず、何も失わないまま縁へと押しやられるためです。',
    tags: ['reproductive', 'zonal-anatomy', 'geometric-model'],
    load: () => import('../scenes/reproductive/scenes/benignProstaticEnlargement/index.js'),
  },
  {
    id: 'biliary-obstruction',
    slug: 'biliary-obstruction',
    titleEn: 'Biliary obstruction',
    titleJa: '胆道閉塞',
    system: 'hepatobiliary',
    organ: 'gallbladder',
    organs: ['gallbladder', 'liver', 'pancreas'],
    disease: 'biliary-obstruction',
    conditions: ['biliary obstruction', 'gallstone', 'choledocholithiasis', 'cystic duct obstruction', 'ampullary obstruction', '胆道閉塞', '胆石', '総胆管結石', '胆嚢管閉塞', '乳頭部閉塞'],
    uses: ['education', 'clinical-learning'],
    status: 'alpha',
    modelCard: 'docs/model-cards/biliary-obstruction.md',
    modelProfile: 'biliary-obstruction-site',
    description:
      'Four resistances from the liver to the gut: why a blockage in the cystic duct, the common bile duct and the papilla do three different things, and why only the last of them reaches the pancreatic duct.',
    descriptionJa:
      '肝臓から腸までを 4 つの抵抗として解き、胆嚢管・総胆管・乳頭部の閉塞が三者三様に異なる結果をもたらす理由と、膵管に及ぶのが最後の一つだけである理由を示します。',
    tags: ['hepatobiliary', 'obstruction', 'scenario-model'],
    load: () => import('../scenes/hepatobiliary/scenes/biliaryObstruction/index.js'),
  },
  {
    id: 'hepatorenal-syndrome',
    slug: 'hepatorenal-syndrome',
    titleEn: 'Hepatorenal syndrome — the haemodynamic mechanism',
    titleJa: '肝腎症候群（HRS-AKI）― 循環からみる腎機能低下',
    system: 'renal',
    organ: 'kidney',
    organs: ['kidney', 'liver'],
    disease: 'hepatorenal-syndrome',
    conditions: ['hepatorenal syndrome', 'HRS', 'HRS-AKI', '肝腎症候群'],
    uses: ['education', 'clinical-learning'],
    status: 'alpha',
    modelCard: 'docs/model-cards/hepatorenal-syndrome.md',
    modelProfile: 'hepatorenal-two-organ-circulation',
    description:
      'Two organs solved as one circulation. It isolates the haemodynamic and neurohumoral component of HRS-AKI — how far the circulation alone can take glomerular filtration — and models no kidney injury, which is a boundary of the model rather than a claim about the syndrome.',
    descriptionJa:
      '2 つの臓器を 1 つの循環として解き、HRS-AKI のうち循環・神経体液性の機序を分離して、循環だけで糸球体濾過量がどこまで低下し得るかを示します。腎障害は実装していませんが、これはモデルの境界であって症候群についての主張ではありません。',
    tags: ['haemodynamics', 'cross-organ', 'treatment-mechanism'],
    load: () => import('../scenes/renal/scenes/hepatorenalSyndrome/index.js'),
  },
  {
    id: 'kidney-anatomy',
    slug: 'kidney-anatomy',
    titleEn: 'Interactive kidney anatomy',
    titleJa: '触れて学ぶ腎臓の解剖',
    system: 'renal',
    organ: 'kidney',
    organs: ['kidney', 'ureter', 'bladder'],
    disease: null,
    conditions: ['kidney anatomy', 'renal pyramids', 'renal columns', 'calyces', '腎解剖', '髄質錐体', '腎杯'],
    status: 'alpha',
    modelCard: 'docs/model-cards/kidney-anatomy.md',
    modelProfile: 'kidney-anatomy-procedural-atlas',
    description:
      'The cortex as one shell, seven medullary pyramids and the cortical columns between them, and a minor calyx on every papilla draining to one pelvis and out as the ureter.',
    descriptionJa:
      '1枚のシェルとしての皮質、7つの髄質錐体とそのあいだの腎柱、各腎乳頭を包む小腎杯から腎盂・尿管へ至る集合系を表示します。',
    tags: ['anatomy', 'interactive', 'collecting-system'],
    relatedScenes: ['renal-filtration'],
    related: {
      scenes: [
        {
          slug: 'renal-filtration',
          // A real part of this kidney, drawn larger — the other kind of
          // scale change from the brain's schematic. `relatedContract.js`.
          transitionType: 'scale-change',
          scaleRelationship: 'magnified-detail',
          label: 'Filtration — one nephron, and what it can hide',
          labelJa: '濾過 — ネフロン 1 本と、それが隠せてしまうもの',
          why: '**A different model, and a different scale.** One nephron, not this kidney magnified.',
          whyJa: '**別のモデルで、縮尺も違います。** ネフロン 1 本であって、この腎臓を拡大したものではありません。',
        },
        {
          slug: 'hepatorenal-syndrome',
          label: 'Hepatorenal syndrome — a kidney failing for a reason outside it',
          labelJa: '肝腎症候群 — 腎臓の外に理由がある腎不全',
          why: '**A different model.** The kidney here is one term in a circulation, not an organ you can name parts of.',
          whyJa: '**別のモデルです。** ここでの腎臓は循環のなかの 1 項で、部位を名前で指せる臓器ではありません。',
        },
      ],
      note:
        '**None of these is this atlas later.** Each is a separate schematic model with its own geometry, built to show a mechanism rather than a specimen. Nothing is deformed, cut or joined to resemble the other, and no measurement crosses between them.',
      noteJa:
        '**どれも「このアトラスのその後」ではありません。** それぞれ独自の形状を持つ別の模式モデルで、標本ではなく仕組みを見せるために作られています。片方をもう片方に似せるための変形・切断・接合はしていませんし、計測値がまたいで使われることもありません。',
    },
    load: () => import('../scenes/renal/scenes/kidneyAnatomy/index.js'),
  },
  {
    id: 'renal-filtration',
    slug: 'renal-filtration',
    titleEn: 'AKI, CKD and nephrotic syndrome',
    titleJa: 'AKI・CKD・ネフローゼ症候群',
    storyTitleEn: 'Where filtration fails',
    storyTitleJa: '濾過は、どこで落ちるのか',
    system: 'renal',
    organ: 'kidney',
    organs: ['kidney'],
    disease: 'renal-dysfunction',
    conditions: ['acute kidney injury', 'AKI', 'prerenal AKI', 'tubular injury', 'urinary obstruction', 'chronic kidney disease', 'CKD', 'nephrotic syndrome', '急性腎障害', '慢性腎臓病', 'ネフローゼ症候群', '腎前性', '尿路閉塞'],
    uses: ['education', 'clinical-learning'],
    status: 'alpha',
    modelCard: 'docs/model-cards/renal-filtration.md',
    modelProfile: 'renal-filtration-starling-mass-balance',
    description:
      'The Starling balance across one glomerular capillary and the tubular mass balance below it, solved together. FENa, the urea-to-creatinine ratio, urine sodium and urine osmolality are not four facts to memorise here — they are four readings of the same solve, which is what lets a reader move a mechanism and watch which of them inverts.',
    descriptionJa:
      '1 本の糸球体毛細血管の Starling 平衡と、その下流の尿細管の物質収支を同時に解きます。FENa・BUN/Cr 比・尿中 Na・尿浸透圧は覚えるべき 4 つの事実ではなく、同じ解の 4 つの読み方です。機序を 1 つ動かして、どれが逆転するのかを確かめられます。',
    tags: ['mass-balance', 'filtration', 'learning-module'],
    relatedScenes: ['kidney-anatomy'],
    load: () => import('../scenes/renal/scenes/renalFiltration/index.js'),
  },
  {
    id: 'biliary-anatomy',
    slug: 'biliary-anatomy',
    titleEn: 'Interactive biliary anatomy',
    titleJa: '触れて学ぶ胆道の解剖',
    system: 'hepatobiliary',
    organ: 'gallbladder',
    organs: ['gallbladder', 'small-intestine'],
    disease: null,
    conditions: ['biliary anatomy', 'gallbladder', 'common bile duct', 'cystic duct', '胆道解剖', '胆嚢', '総胆管', '胆嚢管'],
    status: 'alpha',
    modelCard: 'docs/model-cards/biliary-anatomy.md',
    modelProfile: 'biliary-anatomy-procedural-atlas',
    description:
      'Gallbladder, cystic duct, hepatic ducts and common bile duct in the order they join — which is what decides where an obstruction has to be for a particular thing to go wrong.',
    descriptionJa:
      '胆嚢・胆嚢管・肝管・総胆管を合流の順序どおりに示します。どこが詰まると何が起こるかを決めているのは、この順序です。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/hepatobiliary/scenes/biliaryAnatomy/index.js'),
  },
  {
    id: 'liver-portal-flow',
    slug: 'liver-portal-flow',
    titleEn: 'Portal flow & bile',
    titleJa: '門脈血流と胆汁',
    system: 'hepatobiliary',
    organ: 'liver',
    organs: ['liver', 'gallbladder'],
    disease: null,
    status: 'prototype',
    description: 'Portal inflow crossing the lobes to the hepatic veins, and the gallbladder emptying.',
    descriptionJa: '門脈から流入した血液が肝葉を通り肝静脈へ抜ける流れと、胆嚢の収縮を示します。',
    tags: ['flow', 'particles'],
    load: () => import('../scenes/hepatobiliary/scenes/liverPortalFlow/index.js'),
  },
  {
    id: 'pancreas-anatomy',
    slug: 'pancreas-anatomy',
    titleEn: 'Interactive pancreatic anatomy',
    titleJa: '触れて学ぶ膵臓の解剖',
    system: 'hepatobiliary',
    organ: 'pancreas',
    organs: ['pancreas', 'small-intestine'],
    disease: null,
    conditions: ['pancreas anatomy', 'pancreatic duct', 'islets of Langerhans', '膵解剖', '主膵管', '膵島'],
    status: 'alpha',
    modelCard: 'docs/model-cards/pancreas-anatomy.md',
    modelProfile: 'pancreas-anatomy-procedural-atlas',
    description:
      'Head, neck, body and tail as separate parts, the duct that runs the whole length of them, and endocrine tissue scattered through the exocrine.',
    descriptionJa:
      '膵頭部・頸部・体部・尾部を別々の部位として表示し、全長を貫く主膵管と、外分泌組織の中に散在する内分泌組織を示します。',
    tags: ['anatomy', 'interactive', 'endocrine'],
    relatedScenes: ['pancreatic-secretion'],
    load: () => import('../scenes/hepatobiliary/scenes/pancreasAnatomy/index.js'),
  },
  {
    id: 'pancreatic-secretion',
    slug: 'pancreatic-secretion',
    titleEn: 'Pancreatic secretion',
    titleJa: '膵臓の分泌',
    system: 'hepatobiliary',
    organ: 'pancreas',
    disease: null,
    status: 'prototype',
    description: 'The two outputs of one gland: enzymes into the duct, insulin into the blood.',
    descriptionJa: '1 つの臓器がもつ 2 つの分泌 — 膵管への外分泌と、血中への内分泌を示します。',
    tags: ['secretion', 'endocrine', 'exocrine'],
    relatedScenes: ['pancreas-anatomy'],
    load: () => import('../scenes/hepatobiliary/scenes/pancreaticSecretion/index.js'),
  },
  {
    id: 'bladder-anatomy',
    slug: 'bladder-anatomy',
    titleEn: 'Interactive bladder anatomy',
    titleJa: '触れて学ぶ膀胱の解剖',
    system: 'renal',
    organ: 'bladder',
    organs: ['bladder', 'ureter'],
    disease: null,
    conditions: ['bladder anatomy', 'trigone', 'ureteric orifice', '膀胱解剖', '膀胱三角', '尿管口'],
    status: 'alpha',
    modelCard: 'docs/model-cards/bladder-anatomy.md',
    modelProfile: 'bladder-anatomy-procedural-atlas',
    description:
      'Apex, body, fundus and neck from outside — then fade the wall and find the trigone and its three openings on the inside of the base.',
    descriptionJa:
      '外から膀胱尖・体・底・頸を見たあと、壁を薄くして、膀胱底の内面にある膀胱三角と3つの開口部を見つけます。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/renal/scenes/bladderAnatomy/index.js'),
  },
  {
    id: 'urinary-filtration',
    slug: 'urinary-filtration',
    titleEn: 'Filtration to bladder',
    titleJa: '濾過から膀胱まで',
    system: 'renal',
    organ: 'kidney',
    organs: ['kidney', 'ureter', 'bladder'],
    disease: null,
    status: 'prototype',
    description: 'Filtrate leaving the kidneys, travelling the ureters, and the bladder filling.',
    descriptionJa: '腎で濾過された尿が尿管を下り、膀胱が充満していく流れを示します。',
    tags: ['flow', 'filling'],
    load: () => import('../scenes/renal/scenes/urinaryFiltration/index.js'),
  },
  {
    id: 'thyroid-anatomy',
    slug: 'thyroid-anatomy',
    titleEn: 'Interactive thyroid anatomy',
    titleJa: '触れて学ぶ甲状腺の解剖',
    system: 'endocrine',
    organ: 'thyroid',
    organs: ['thyroid'],
    disease: null,
    conditions: ['thyroid anatomy', 'parathyroid glands', 'recurrent laryngeal nerve', '甲状腺解剖', '副甲状腺', '反回神経'],
    status: 'alpha',
    modelCard: 'docs/model-cards/thyroid-anatomy.md',
    modelProfile: 'thyroid-anatomy-procedural-atlas',
    description:
      'Two lobes and the isthmus clasped around the trachea — then fade the gland and find the four parathyroids and the two recurrent laryngeal nerves behind it.',
    descriptionJa:
      '気管を抱き込む左右の葉と峡部を表示し、甲状腺を薄くすると、その背面にある4つの副甲状腺と左右の反回神経が現れます。',
    tags: ['anatomy', 'interactive', 'endocrine'],
    load: () => import('../scenes/endocrine/scenes/thyroidAnatomy/index.js'),
  },
  {
    id: 'thyroid-hormone',
    slug: 'thyroid-hormone',
    titleEn: 'Thyroid hormone release',
    titleJa: '甲状腺ホルモンの放出',
    system: 'endocrine',
    organ: 'thyroid',
    disease: null,
    status: 'prototype',
    description: 'Follicles releasing hormone into the surrounding capillaries as stimulation rises.',
    descriptionJa: '刺激の増加にあわせ、濾胞から周囲の毛細血管へホルモンが放出される様子を示します。',
    tags: ['secretion', 'particles'],
    load: () => import('../scenes/endocrine/scenes/thyroidHormone/index.js'),
  },
  {
    id: 'adrenal-anatomy',
    slug: 'adrenal-anatomy',
    titleEn: 'Interactive adrenal anatomy',
    titleJa: '触れて学ぶ副腎の解剖',
    system: 'endocrine',
    organ: 'adrenal',
    organs: ['adrenal', 'kidney'],
    disease: null,
    conditions: ['adrenal anatomy', 'zona glomerulosa', 'adrenal medulla', '副腎解剖', '球状層', '副腎髄質'],
    status: 'alpha',
    modelCard: 'docs/model-cards/adrenal-anatomy.md',
    modelProfile: 'adrenal-anatomy-procedural-atlas',
    description:
      'Three cortical zones and, inside them, nervous tissue that is not cortex at all \u2014 one organ made of two entirely different things.',
    descriptionJa:
      '皮質の3層と、その内側にある皮質とは全く別の神経系組織を示します。1つの臓器が、まったく異なる2つの組織でできています。',
    tags: ['anatomy', 'interactive', 'endocrine'],
    load: () => import('../scenes/endocrine/scenes/adrenalAnatomy/index.js'),
  },
  {
    id: 'adrenal-response',
    slug: 'adrenal-response',
    titleEn: 'Adrenal response',
    titleJa: '副腎の反応',
    system: 'endocrine',
    organ: 'adrenal',
    disease: null,
    status: 'prototype',
    description: 'Cortex and medulla as two layers with two different release time-courses.',
    descriptionJa: '皮質と髄質という 2 層が、異なる時間経過で分泌する様子を示します。',
    tags: ['secretion', 'layers'],
    load: () => import('../scenes/endocrine/scenes/adrenalResponse/index.js'),
  },
  {
    id: 'spleen-anatomy',
    slug: 'spleen-anatomy',
    titleEn: 'Interactive splenic anatomy',
    titleJa: '触れて学ぶ脾臓の解剖',
    system: 'hematologic',
    organ: 'spleen',
    organs: ['spleen'],
    disease: null,
    conditions: ['spleen anatomy', 'splenic segments', 'splenic hilum', '脾臓解剖', '脾区域', '脾門'],
    status: 'alpha',
    modelCard: 'docs/model-cards/spleen-anatomy.md',
    modelProfile: 'spleen-anatomy-procedural-atlas',
    description:
      'The two territories the splenic artery’s terminal branches supply — the one division of this organ that is a solid rather than a stain.',
    descriptionJa:
      '脾動脈の2本の終枝が支配する2つの領域を示します。脾臓で唯一、染色ではなく立体として分けられる区分です。',
    tags: ['anatomy', 'interactive', 'vascular'],
    load: () => import('../scenes/hematologic/scenes/spleenAnatomy/index.js'),
  },
  {
    id: 'spleen-filtration',
    slug: 'spleen-filtration',
    titleEn: 'Splenic filtration',
    titleJa: '脾臓での血球処理',
    system: 'hematologic',
    organ: 'spleen',
    disease: null,
    status: 'prototype',
    description: 'Red cells crossing the red pulp; aged cells retained rather than returned.',
    descriptionJa: '赤脾髄を通過する赤血球のうち、老化した赤血球が捕捉される様子を示します。',
    tags: ['flow', 'particles'],
    load: () => import('../scenes/hematologic/scenes/spleenFiltration/index.js'),
  },
  {
    id: 'knee-anatomy',
    slug: 'knee-anatomy',
    titleEn: 'Interactive knee anatomy',
    titleJa: '触れて学ぶ膝関節の解剖',
    system: 'musculoskeletal',
    organ: 'knee',
    organs: ['knee', 'bone'],
    disease: null,
    conditions: ['knee anatomy', 'cruciate ligament', 'meniscus', 'collateral ligament', '膝関節解剖', '十字靱帯', '半月板', '側副靱帯'],
    status: 'alpha',
    modelCard: 'docs/model-cards/knee-anatomy.md',
    modelProfile: 'knee-anatomy-procedural-atlas',
    description:
      'Femur on tibia, cartilage over every surface that meets another, both menisci between them, and the four ligaments that decide what the joint will and will not do.',
    descriptionJa:
      '脛骨の上の大腿骨、接する面を覆う関節軟骨、その間の半月板、そして関節の動きを決める4本の靱帯を示します。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/musculoskeletal/scenes/kneeAnatomy/index.js'),
  },
  {
    id: 'shoulder-anatomy',
    slug: 'shoulder-anatomy',
    titleEn: 'Interactive shoulder anatomy',
    titleJa: '触れて学ぶ肩関節の解剖',
    system: 'musculoskeletal',
    organ: 'shoulder',
    organs: ['shoulder', 'bone'],
    disease: null,
    conditions: ['shoulder anatomy', 'rotator cuff', 'glenoid', 'labrum', 'subacromial', '肩関節解剖', '腱板', '関節窩', '関節唇'],
    status: 'alpha',
    modelCard: 'docs/model-cards/shoulder-anatomy.md',
    modelProfile: 'shoulder-anatomy-procedural-atlas',
    description:
      'A large head on a small socket, the four cuff tendons that hold it there, and the arch of bone and ligament they pass under.',
    descriptionJa:
      '小さな関節窩に対する大きな上腕骨頭、それを保持する腱板4筋の腱、そしてその腱が通る骨と靱帯のアーチを示します。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/musculoskeletal/scenes/shoulderAnatomy/index.js'),
  },
  {
    id: 'hip-anatomy',
    slug: 'hip-anatomy',
    titleEn: 'Interactive hip anatomy',
    titleJa: '触れて学ぶ股関節の解剖',
    system: 'musculoskeletal',
    organ: 'hip',
    organs: ['hip', 'bone'],
    disease: null,
    conditions: ['hip anatomy', 'acetabulum', 'femoral neck', 'labrum', 'iliofemoral ligament', '股関節解剖', '臼蓋', '大腿骨頸部', '関節唇'],
    status: 'alpha',
    modelCard: 'docs/model-cards/hip-anatomy.md',
    modelProfile: 'hip-anatomy-procedural-atlas',
    description:
      'A socket that grips past the widest part of the head, and a neck that holds the head out to the side of the bone carrying the weight.',
    descriptionJa:
      '骨頭の最大径より先まで達する臼蓋と、荷重を支える骨幹から骨頭を側方に離して支える頸部を示します。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/musculoskeletal/scenes/hipAnatomy/index.js'),
  },
  {
    id: 'eye-anatomy',
    slug: 'eye-anatomy',
    titleEn: 'Interactive eye anatomy',
    titleJa: '触れて学ぶ眼の解剖',
    system: 'sensory',
    organ: 'eye',
    organs: ['eye'],
    disease: null,
    conditions: ['eye anatomy', 'retina', 'macula', 'optic disc', 'cornea', 'anterior chamber', '眼の解剖', '網膜', '黄斑', '視神経乳頭', '角膜', '前房'],
    status: 'alpha',
    modelCard: 'docs/model-cards/eye-anatomy.md',
    modelProfile: 'eye-anatomy-procedural-atlas',
    description:
      'Three coats around three transparent things, the angle the fluid in front leaves by, and a fundus with its disc nasal and its macula temporal.',
    descriptionJa:
      '3つの膜と3つの透明な内容、前房水が流出する隅角、そして鼻側に視神経乳頭・耳側に黄斑をもつ眼底を示します。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/sensory/scenes/eyeAnatomy/index.js'),
  },
  {
    id: 'ear-anatomy',
    slug: 'ear-anatomy',
    titleEn: 'Interactive ear anatomy',
    titleJa: '触れて学ぶ耳の解剖',
    system: 'sensory',
    organ: 'ear',
    organs: ['ear'],
    disease: null,
    conditions: ['ear anatomy', 'ossicles', 'cochlea', 'eustachian tube', 'tympanic membrane', '耳の解剖', '耳小骨', '蝸牛', '耳管', '鼓膜'],
    status: 'alpha',
    modelCard: 'docs/model-cards/ear-anatomy.md',
    modelProfile: 'ear-anatomy-procedural-atlas',
    description:
      'Air, then bone, then fluid: a funnel to a drum, three bones on a lever across an air space, and a spiral with three loops behind it.',
    descriptionJa:
      '空気・骨・液体と続く伝達経路。鼓膜までの漏斗、含気腔を横切る3つの耳小骨、その奥のらせんと3つのループを示します。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/sensory/scenes/earAnatomy/index.js'),
  },
  {
    id: 'skin-anatomy',
    slug: 'skin-anatomy',
    titleEn: 'Interactive skin anatomy',
    titleJa: '触れて学ぶ皮膚の解剖',
    system: 'integumentary',
    organ: 'skin',
    organs: ['skin'],
    disease: null,
    conditions: ['skin anatomy', 'epidermis', 'dermis', 'hair follicle', 'sweat gland', '皮膚の解剖', '表皮', '真皮', '毛包', '汗腺'],
    status: 'alpha',
    modelCard: 'docs/model-cards/skin-anatomy.md',
    modelProfile: 'skin-anatomy-procedural-atlas',
    description:
      'A block with its sides cut: three layers, a follicle down into the fat, two different routes to the surface, and vessels that stop at the epidermis.',
    descriptionJa:
      '側面を切り出した1ブロック。3つの層、脂肪層まで達する毛包、体表への2つの異なる経路、そして表皮の手前で終わる血管を示します。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/integumentary/scenes/skinAnatomy/index.js'),
  },
  {
    id: 'lymph-node-anatomy',
    slug: 'lymph-node-anatomy',
    titleEn: 'Interactive lymph node anatomy',
    titleJa: '触れて学ぶリンパ節の解剖',
    system: 'hematologic',
    organ: 'lymph-node',
    organs: ['lymph-node'],
    disease: null,
    conditions: ['lymph node anatomy', 'cortex', 'medulla', 'afferent lymphatic', 'hilum', 'リンパ節の解剖', '皮質', '髄質', '輸入リンパ管', '門'],
    status: 'alpha',
    modelCard: 'docs/model-cards/lymph-node-anatomy.md',
    modelProfile: 'lymph-node-anatomy-procedural-atlas',
    description:
      'Many vessels in, one out — so lymph passes through a node rather than round it, and what arrives has nowhere else to go.',
    descriptionJa:
      '多数の輸入リンパ管と1本の輸出リンパ管。リンパは節を迂回できず必ず内部を通過するため、到達したものはここに留まります。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/hematologic/scenes/lymphNodeAnatomy/index.js'),
  },
  {
    id: 'lymphatic-drainage',
    slug: 'lymphatic-drainage',
    titleEn: 'Where lymph drains',
    titleJa: 'リンパはどこへ流れるか',
    system: 'hematologic',
    organ: 'lymphatic-system',
    organs: ['lymphatic-system', 'lymph-node'],
    disease: null,
    conditions: ['lymphatic drainage', 'thoracic duct', 'axillary nodes', 'cervical nodes', 'inguinal nodes', 'リンパ流', '胸管', '腋窩リンパ節', '頸部リンパ節', '鼠径リンパ節'],
    status: 'alpha',
    modelCard: 'docs/model-cards/lymphatic-drainage.md',
    modelProfile: 'lymphatic-drainage-procedural-atlas',
    description:
      'One short duct takes a quarter of the body and one long one takes the rest — so which side a place drains to decides where anything travelling in lymph turns up.',
    descriptionJa:
      '短い右リンパ本幹が体の約1/4を、長い胸管が残りを受けます。どちら側に流れる部位かによって、リンパ行性に広がるものが現れる場所が決まります。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/hematologic/scenes/lymphaticDrainage/index.js'),
  },
  {
    id: 'breast-anatomy',
    slug: 'breast-anatomy',
    titleEn: 'Interactive breast anatomy',
    titleJa: '触れて学ぶ乳房の解剖',
    system: 'reproductive',
    organ: 'breast',
    organs: ['breast', 'lymph-node'],
    disease: null,
    conditions: ['breast anatomy', 'lactiferous duct', 'lobule', 'Cooper ligament', 'axillary drainage', '乳房の解剖', '乳管', '小葉', 'クーパー靱帯', '腋窩リンパ流'],
    status: 'alpha',
    modelCard: 'docs/model-cards/breast-anatomy.md',
    modelProfile: 'breast-anatomy-procedural-atlas',
    description:
      'Ducts converging on one place, lobules at the far end of each, strands reaching the skin, and a tail running out to the armpit.',
    descriptionJa:
      '1か所に収束する乳管、その末端の小葉、皮膚に達する支持索、そして腋窩へ伸びる乳腺の尾部を示します。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/reproductive/scenes/breastAnatomy/index.js'),
  },
  {
    id: 'spine-anatomy',
    slug: 'spine-anatomy',
    titleEn: 'Interactive spine anatomy',
    titleJa: '触れて学ぶ脊柱の解剖',
    system: 'musculoskeletal',
    organ: 'spine',
    organs: ['spine', 'bone'],
    disease: null,
    conditions: ['spine anatomy', 'intervertebral disc', 'nucleus pulposus', 'spinal canal', 'nerve root', 'cauda equina', '脊柱の解剖', '椎間板', '髄核', '脊柱管', '神経根', '馬尾'],
    status: 'alpha',
    modelCard: 'docs/model-cards/spine-anatomy.md',
    modelProfile: 'spine-anatomy-procedural-atlas',
    description:
      'Four regions and three curves, with one lumbar level drawn in full: body, pedicles, laminae, facets, disc, canal and the roots leaving it.',
    descriptionJa:
      '4つの部位と3つの弯曲、そして詳細に描いた腰椎1椎間——椎体・椎弓根・椎弓板・椎間関節・椎間板・脊柱管と、そこを出る神経根を示します。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/musculoskeletal/scenes/spineAnatomy/index.js'),
  },
  {
    id: 'nose-anatomy',
    slug: 'nose-anatomy',
    titleEn: 'Interactive nose and sinus anatomy',
    titleJa: '触れて学ぶ鼻・副鼻腔の解剖',
    system: 'respiratory',
    organ: 'nose',
    organs: ['nose'],
    disease: null,
    conditions: ['nasal anatomy', 'paranasal sinuses', 'turbinates', 'middle meatus', 'maxillary sinus', 'olfactory region', '鼻の解剖', '副鼻腔', '鼻甲介', '中鼻道', '上顎洞', '嗅部'],
    status: 'alpha',
    modelCard: 'docs/model-cards/nose-anatomy.md',
    modelProfile: 'nose-anatomy-procedural-atlas',
    description:
      'A cavity that is a slit with three shelves in it, and four air-filled rooms that drain into the gutters below them — one of them uphill.',
    descriptionJa:
      '3つの鼻甲介が張り出す狭い鼻腔と、その下の鼻道へ開口する4つの副鼻腔。上顎洞の自然孔が底ではなく天井近くにあることを示します。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/respiratory/scenes/noseAnatomy/index.js'),
  },
  {
    id: 'larynx-anatomy',
    slug: 'larynx-anatomy',
    titleEn: 'Interactive larynx and pharynx anatomy',
    titleJa: '触れて学ぶ喉頭・咽頭の解剖',
    system: 'respiratory',
    organ: 'larynx',
    organs: ['larynx', 'pharynx'],
    disease: null,
    conditions: ['larynx anatomy', 'pharynx', 'vocal folds', 'epiglottis', 'cricothyroid membrane', 'piriform sinus', '喉頭の解剖', '咽頭', '声帯', '喉頭蓋', '輪状甲状膜', '梨状陥凹'],
    status: 'alpha',
    modelCard: 'docs/model-cards/larynx-anatomy.md',
    modelProfile: 'larynx-anatomy-procedural-atlas',
    description:
      'For a few centimetres air and food share one space, and the larynx sits in the front wall of it — with a gutter down each side carrying a swallow round the outside of the airway.',
    descriptionJa:
      '空気と食物が数センチだけ1つの通り道を共有する場所。喉頭はその前壁にあり、両側の梨状陥凹が嚥下物を気道の外側へ回します。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/respiratory/scenes/larynxAnatomy/index.js'),
  },
  {
    id: 'oral-anatomy',
    slug: 'oral-anatomy',
    titleEn: 'Interactive mouth and tongue anatomy',
    titleJa: '触れて学ぶ口腔・舌の解剖',
    system: 'gastrointestinal',
    organ: 'mouth',
    organs: ['mouth', 'tongue'],
    disease: null,
    conditions: ['oral anatomy', 'tongue', 'salivary glands', 'palatine tonsil', 'frenulum', 'parotid duct', '口腔の解剖', '舌', '唾液腺', '口蓋扁桃', '舌小帯', '耳下腺管'],
    status: 'alpha',
    modelCard: 'docs/model-cards/oral-anatomy.md',
    modelProfile: 'oral-anatomy-procedural-atlas',
    description:
      'A line across the tongue divides two parts with different nerves, and three pairs of glands outside the mouth open into it at places nowhere near themselves.',
    descriptionJa:
      '舌を横切る1本の線が、神経支配の異なる2つの部分を分けます。口腔の外にある3対の唾液腺は、それぞれ腺から遠く離れた位置に開口します。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/gastrointestinal/scenes/oralAnatomy/index.js'),
  },
  {
    id: 'pelvic-floor-anatomy',
    slug: 'pelvic-floor-anatomy',
    titleEn: 'Interactive pelvic floor anatomy',
    titleJa: '触れて学ぶ骨盤底の解剖',
    system: 'musculoskeletal',
    organ: 'pelvic-floor',
    organs: ['pelvic-floor'],
    disease: null,
    conditions: ['pelvic floor', 'levator ani', 'puborectalis', 'urogenital hiatus', 'perineal body', '骨盤底', '肛門挙筋', '恥骨直腸筋', '尿生殖裂孔', '会陰体'],
    status: 'alpha',
    modelCard: 'docs/model-cards/pelvic-floor-anatomy.md',
    modelProfile: 'pelvic-floor-anatomy-procedural-atlas',
    description:
      'A sheet of muscle with a gap in the front of it, and one part that is not a sheet at all but a sling passing behind the bowel.',
    descriptionJa:
      '前方に隙間のある筋のシートと、シートではなく腸管の後方を回る吊り輪。骨盤底の要点はこの2つです。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/musculoskeletal/scenes/pelvicFloorAnatomy/index.js'),
  },
  {
    id: 'hand-anatomy',
    slug: 'hand-anatomy',
    titleEn: 'Interactive hand and wrist anatomy',
    titleJa: '触れて学ぶ手・手関節の解剖',
    system: 'musculoskeletal',
    organ: 'hand',
    organs: ['hand'],
    disease: null,
    conditions: ['hand anatomy', 'carpal bones', 'carpal tunnel', 'scaphoid', 'median nerve', 'flexor tendons', '手の解剖', '手根骨', '手根管', '舟状骨', '正中神経', '屈筋腱'],
    status: 'alpha',
    modelCard: 'docs/model-cards/hand-anatomy.md',
    modelProfile: 'hand-anatomy-procedural-atlas',
    description:
      'Eight small bones make an arch, a band roofs it, and ten things share the space underneath with nowhere to move.',
    descriptionJa:
      '8個の手根骨がつくるアーチに屈筋支帯が蓋をし、その下の逃げ場のない空間を9本の腱と1本の神経が分け合います。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/musculoskeletal/scenes/handAnatomy/index.js'),
  },
  {
    id: 'foot-anatomy',
    slug: 'foot-anatomy',
    titleEn: 'Interactive foot and ankle anatomy',
    titleJa: '触れて学ぶ足・足関節の解剖',
    system: 'musculoskeletal',
    organ: 'foot',
    organs: ['foot'],
    disease: null,
    conditions: ['foot anatomy', 'ankle', 'plantar fascia', 'talus', 'subtalar joint', 'medial arch', '足の解剖', '足関節', '足底腱膜', '距骨', '距骨下関節', '内側縦アーチ'],
    status: 'alpha',
    modelCard: 'docs/model-cards/foot-anatomy.md',
    modelProfile: 'foot-anatomy-procedural-atlas',
    description:
      'A foot is an arch, not a plate: high on the inside, low on the outside, and held from spreading by a band slung from the heel to the toes.',
    descriptionJa:
      '足は板ではなくアーチです。内側が高く外側が低く、踵から中足骨頭へ張る足底腱膜がその広がりを止めています。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/musculoskeletal/scenes/footAnatomy/index.js'),
  },
  {
    id: 'skeleton-overview',
    slug: 'skeleton-overview',
    titleEn: 'The skeleton, whole',
    titleJa: '全身の骨格を俯瞰する',
    system: 'musculoskeletal',
    organ: 'skeleton',
    organs: ['skeleton'],
    disease: null,
    conditions: ['skeleton', 'axial skeleton', 'appendicular skeleton', 'shoulder girdle', 'pelvic girdle', '全身骨格', '体軸骨格', '四肢骨格', '上肢帯', '下肢帯'],
    status: 'alpha',
    modelCard: 'docs/model-cards/skeleton-overview.md',
    modelProfile: 'skeleton-overview-procedural-atlas',
    description:
      'A skeleton is two skeletons — a column, and limbs hung off it. The arm hangs by one small joint; the leg is locked into the spine itself.',
    descriptionJa:
      '骨格は「体軸」と「そこに吊られた四肢」の2つでできています。腕は1つの小さな関節で付き、脚は脊柱そのものに固定されています。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/musculoskeletal/scenes/skeletonOverview/index.js'),
  },
  {
    id: 'bone-remodeling',
    slug: 'bone-remodeling',
    titleEn: 'Bone remodelling',
    titleJa: '骨のリモデリング',
    system: 'musculoskeletal',
    organ: 'bone',
    disease: null,
    status: 'prototype',
    description:
      'Sequential remodelling at staggered sites: resorption → reversal → formation, with long-term cortical thinning when replacement falls behind.',
    descriptionJa:
      '各部位で吸収 → 反転期 → 形成と順に進むリモデリング。形成が吸収に追いつかない状態が長期に続くと皮質骨が菲薄化する様子を示します。',
    tags: ['turnover', 'particles'],
    load: () => import('../scenes/musculoskeletal/scenes/boneRemodeling/index.js'),
  },
  {
    id: 'muscle-contraction',
    slug: 'muscle-contraction',
    titleEn: 'Muscle contraction',
    titleJa: '骨格筋の収縮',
    system: 'musculoskeletal',
    organ: 'skeletal-muscle',
    disease: null,
    status: 'prototype',
    description: 'A muscle belly shortening and thickening between its tendons as recruitment rises.',
    descriptionJa: '動員が増えるにつれ、腱の間で筋腹が短縮し太くなる様子を示します。',
    tags: ['contraction', 'recruitment'],
    load: () => import('../scenes/musculoskeletal/scenes/muscleContraction/index.js'),
  },
  {
    id: 'uterus-anatomy',
    slug: 'uterus-anatomy',
    titleEn: 'Interactive uterine anatomy',
    titleJa: '触れて学ぶ子宮の解剖',
    system: 'reproductive',
    organ: 'uterus',
    organs: ['uterus'],
    disease: null,
    conditions: ['uterus anatomy', 'uterine cavity', 'fallopian tube', '子宮解剖', '子宮腔', '卵管'],
    status: 'alpha',
    modelCard: 'docs/model-cards/uterus-anatomy.md',
    modelProfile: 'uterus-anatomy-procedural-atlas',
    description:
      'Fundus, body, isthmus and cervix, a tube reaching towards each ovary without touching it \u2014 then fade the wall and the cavity is a flattened triangle, not a bag.',
    descriptionJa:
      '子宮底・体部・峡部・頸部と、卵巣に触れずに向かい合う左右の卵管を示します。子宮壁を薄くすると、内腔が袋ではなく扁平な三角形であることが見えます。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/reproductive/scenes/uterusAnatomy/index.js'),
  },
  {
    id: 'uterine-cycle',
    slug: 'uterine-cycle',
    titleEn: 'Endometrial cycle',
    titleJa: '子宮内膜の周期',
    system: 'reproductive',
    organ: 'uterus',
    disease: null,
    status: 'prototype',
    description: 'Endometrial thickness across one cycle, in section.',
    descriptionJa: '1 周期を通じた子宮内膜の厚さの変化を、断面で示します。',
    tags: ['cycle', 'section'],
    load: () => import('../scenes/reproductive/scenes/uterineCycle/index.js'),
  },
  {
    id: 'prostate-anatomy',
    slug: 'prostate-anatomy',
    titleEn: 'Interactive prostatic anatomy',
    titleJa: '触れて学ぶ前立腺の解剖',
    system: 'reproductive',
    organ: 'prostate',
    organs: ['prostate', 'bladder'],
    disease: null,
    conditions: ['prostate anatomy', 'peripheral zone', 'transition zone', 'ejaculatory duct', '前立腺解剖', '末梢域', '移行域', '射精管'],
    status: 'alpha',
    modelCard: 'docs/model-cards/prostate-anatomy.md',
    modelProfile: 'prostate-anatomy-procedural-atlas',
    description:
      'Peripheral zone outside, transition and central zones inside, and the urethra and ejaculatory ducts running through them \u2014 which zone a thing is in is what prostate disease turns on.',
    descriptionJa:
      '外側の末梢域、内側の移行域と中心域、そしてそこを貫く尿道と射精管を示します。前立腺の疾患は「どの領域か」で決まります。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/reproductive/scenes/prostateAnatomy/index.js'),
  },
  {
    id: 'male-tract-anatomy',
    slug: 'male-tract-anatomy',
    titleEn: 'The male genital tract, end to end',
    titleJa: '男性生殖路の全体像',
    system: 'reproductive',
    organ: 'prostate',
    organs: ['prostate', 'bladder'],
    disease: null,
    conditions: ['male reproductive anatomy', 'vas deferens', 'epididymis', 'urethra', '男性生殖器', '精管', '精巣上体', '尿道'],
    status: 'alpha',
    modelCard: 'docs/model-cards/male-tract-anatomy.md',
    modelProfile: 'male-tract-anatomy-procedural-atlas',
    description:
      'Testis, epididymis, vas, ejaculatory duct and three lengths of urethra as one continuous route \u2014 what connects to what, and where each connection can be interrupted.',
    descriptionJa:
      '精巣・精巣上体・精管・射精管・尿道3部を1本の連続した経路として示します。何が何につながり、どこで断てるのかが分かります。',
    tags: ['anatomy', 'interactive'],
    load: () => import('../scenes/reproductive/scenes/maleTractAnatomy/index.js'),
  },
  {
    id: 'prostate-outflow',
    slug: 'prostate-outflow',
    titleEn: 'Prostate & outflow',
    titleJa: '前立腺と尿流',
    system: 'reproductive',
    organ: 'prostate',
    disease: null,
    status: 'prototype',
    description: 'Prostatic volume against the calibre of the urethra running through it.',
    descriptionJa: '前立腺の体積と、その中を通る尿道の内径の関係を示します。',
    tags: ['obstruction', 'flow'],
    load: () => import('../scenes/reproductive/scenes/prostateOutflow/index.js'),
  },
  {
    id: 'body-overview',
    slug: 'body-overview',
    titleEn: 'Human body overview',
    titleJa: '全身の概観',
    system: 'systemic',
    organ: 'whole-body',
    organs: [
      'whole-body',
      'brain',
      'heart',
      'lungs',
      'liver',
      'stomach',
      'kidney',
      'small-intestine',
      'colon',
      'bladder',
    ],
    disease: null,
    status: 'prototype',
    description: 'Where the organ scenes sit relative to one another, built from the same organ builders.',
    descriptionJa: '各臓器シーンの位置関係を、同じ臓器ジオメトリを再利用して 1 つのビューに示します。',
    tags: ['overview', 'orientation'],
    load: () => import('../scenes/systemic/scenes/bodyOverview/index.js'),
  },
];

/**
 * Disease scenes this architecture exists for, none of them built yet.
 *
 * They are listed — not implemented — so that the explorer shows the direction
 * and so that the split between "the organ" and "what is wrong with it" is
 * visible before the second scene of an organ arrives. Moving one of these into
 * `SCENE_MANIFEST` is the whole ceremony of adding a disease scene.
 *
 * This is the promoted tip of a larger triaged pool: candidates start in
 * `docs/disease-candidates.md` and are only listed here once they look like a
 * real question worth a scene.
 */
export const PLANNED_SCENES = [
  { organ: 'lungs', disease: 'pneumothorax', titleEn: 'Pneumothorax', titleJa: '気胸' },
  // Chronic kidney disease, acute kidney injury and nephrotic syndrome are now
  // *situations* inside `renal-filtration` rather than three separate scenes:
  // they share one model, and splitting them would have meant three copies of
  // the same Starling balance. What remains planned is the part that model
  // does not reach — the consequences of failure rather than its mechanism.
  { organ: 'kidney', disease: 'ckd-mineral-bone', titleEn: 'CKD and mineral–bone disease', titleJa: 'CKD と骨・ミネラル代謝異常' },
  { organ: 'kidney', disease: 'hyperkalaemia', titleEn: 'Potassium handling and hyperkalaemia', titleJa: 'カリウム動態と高カリウム血症' },
  { organ: 'liver', disease: 'steatosis', titleEn: 'Steatosis', titleJa: '脂肪肝' },
  { organ: 'liver', disease: 'hepatitis', titleEn: 'Hepatitis', titleJa: '肝炎' },
  { organ: 'brain', disease: 'stroke', titleEn: 'Stroke', titleJa: '脳梗塞' },
  { organ: 'brain', disease: 'parkinsons', titleEn: "Parkinson's disease", titleJa: 'パーキンソン病' },
  { organ: 'brain', disease: 'raised-icp', titleEn: 'Raised intracranial pressure', titleJa: '頭蓋内圧亢進' },
  { organ: 'heart', disease: 'valve-disease', titleEn: 'Valve disease', titleJa: '弁膜症' },
  { organ: 'heart', disease: 'ischemia', titleEn: 'Myocardial ischaemia', titleJa: '心筋虚血' },
  { organ: 'heart', disease: 'atrial-fibrillation', titleEn: 'Atrial fibrillation', titleJa: '心房細動' },
  { organ: 'esophagus', disease: 'achalasia', titleEn: 'Achalasia', titleJa: 'アカラシア' },
  { organ: 'small-intestine', disease: 'bowel-obstruction', titleEn: 'Bowel obstruction', titleJa: '腸閉塞' },
  { organ: 'pancreas', disease: 'diabetes-mellitus', titleEn: 'Diabetes mellitus', titleJa: '糖尿病' },
  { organ: 'ureter', disease: 'ureteric-stone', titleEn: 'Ureteric stone', titleJa: '尿管結石' },
  { organ: 'thyroid', disease: 'hyperthyroidism', titleEn: 'Hyperthyroidism', titleJa: '甲状腺機能亢進症' },
  { organ: 'bone', disease: 'osteoporosis', titleEn: 'Osteoporosis', titleJa: '骨粗鬆症' },
  { organ: 'whole-body', disease: 'septic-shock', titleEn: 'Septic shock', titleJa: '敗血症性ショック' },
];
